sonar.projectKey=jamescrowley321_terraform-provider-descope
sonar.organization=jamescrowley321
sonar.projectName=terraform-provider-descope

sonar.sources=internal/
sonar.tests=internal/
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/vendor/**,**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=test-report.json
