sonar.projectKey=jamescrowley321_terraform-provider-descope
sonar.organization=jamescrowley321
sonar.projectName=terraform-provider-descope

sonar.sources=internal/,tools/
sonar.tests=internal/
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/vendor/**,**/*_test.go,tools/terragen/**

# Skip copy-paste detection on documentation and upstream model code
sonar.cpd.exclusions=internal/docs/**,internal/models/project/**

sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=test-report.json
