name: Check Leaks

description: Check Leaks

inputs:
  gitleaks_license:
    description: "A gitleaks-action license"
    required: true

runs:
  using: composite
  steps:
    - name: Check Leaks
      uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e # v3.0.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITLEAKS_LICENSE: ${{ inputs.gitleaks_license }}
        GITLEAKS_CONFIG: .github/actions/ci/leaks/gitleaks.toml
        GITLEAKS_ENABLE_SUMMARY: "false"
        GITLEAKS_ENABLE_UPLOAD_ARTIFACT: "false"
