// Code generated by terragen. DO NOT EDIT.

package docs

import (
	"fmt"

	"github.com/descope/terraform-provider-descope/internal/models/accesskey"
	"github.com/descope/terraform-provider-descope/internal/models/apppermission"
	"github.com/descope/terraform-provider-descope/internal/models/approle"
	"github.com/descope/terraform-provider-descope/internal/models/apps"
	"github.com/descope/terraform-provider-descope/internal/models/attribute"
	"github.com/descope/terraform-provider-descope/internal/models/connectors"
	"github.com/descope/terraform-provider-descope/internal/models/descoper"
	"github.com/descope/terraform-provider-descope/internal/models/emailtemplate"
	"github.com/descope/terraform-provider-descope/internal/models/engine"
	"github.com/descope/terraform-provider-descope/internal/models/fgaschema"
	"github.com/descope/terraform-provider-descope/internal/models/flow"
	"github.com/descope/terraform-provider-descope/internal/models/inboundapp"
	"github.com/descope/terraform-provider-descope/internal/models/jwttemplate"
	"github.com/descope/terraform-provider-descope/internal/models/list"
	"github.com/descope/terraform-provider-descope/internal/models/managementkey"
	"github.com/descope/terraform-provider-descope/internal/models/oauthprovider"
	"github.com/descope/terraform-provider-descope/internal/models/outboundapp"
	"github.com/descope/terraform-provider-descope/internal/models/permission"
	"github.com/descope/terraform-provider-descope/internal/models/project"
	"github.com/descope/terraform-provider-descope/internal/models/role"
	"github.com/descope/terraform-provider-descope/internal/models/settings"
	"github.com/descope/terraform-provider-descope/internal/models/styles"
	"github.com/descope/terraform-provider-descope/internal/models/texttemplate"
	"github.com/descope/terraform-provider-descope/internal/models/voicetemplate"
	"github.com/descope/terraform-provider-descope/internal/models/widget"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func InjectModels() {
	inject(accesskey.AccessKeyAttributes, docsAccessKey)
	inject(accesskey.AccessKeyTenantAttributes, docsAccessKeyTenant)
	inject(apppermission.AppPermissionAttributes, docsAppPermission)
	inject(approle.AppRoleAttributes, docsAppRole)
	inject(apps.OIDCAppAttributes, docsOIDCApp)
	inject(apps.SAMLAppAttributes, docsSAMLApp)
	inject(apps.DynamicConfigurationAttributes, docsDynamicConfiguration)
	inject(apps.ManualConfigurationAttributes, docsManualConfiguration)
	inject(apps.AttributeMappingAttributes, docsAttributeMapping)
	inject(apps.WSFedAppAttributes, docsWSFedApp)
	inject(apps.GroupsMappingAttributes, docsGroupsMapping)
	inject(apps.RoleGroupMappingAttributes, docsRoleGroupMapping)
	inject(attribute.AccessKeyAttributeAttributes, docsAccessKeyAttribute)
	inject(attribute.WidgetAuthorizationAttributes, docsWidgetAuthorization)
	inject(attribute.TenantAttributeAttributes, docsTenantAttribute)
	inject(attribute.TenantAttributeAuthorizationAttributes, docsTenantAttributeAuthorization)
	inject(attribute.UserAttributeAttributes, docsUserAttribute)
	inject(connectors.AbuseIPDBConnectorAttributes, docsAbuseIPDBConnector)
	inject(connectors.AlloyConnectorAttributes, docsAlloyConnector)
	inject(connectors.AmplitudeConnectorAttributes, docsAmplitudeConnector)
	inject(connectors.ArkoseConnectorAttributes, docsArkoseConnector)
	inject(connectors.AuditWebhookConnectorAttributes, docsAuditWebhookConnector)
	inject(connectors.AWSEventBridgeConnectorAttributes, docsAWSEventBridgeConnector)
	inject(connectors.AWSS3ConnectorAttributes, docsAWSS3Connector)
	inject(connectors.AWSSESEmailValidationConnectorAttributes, docsAWSSESEmailValidationConnector)
	inject(connectors.AWSTranslateConnectorAttributes, docsAWSTranslateConnector)
	inject(connectors.BitsightConnectorAttributes, docsBitsightConnector)
	inject(connectors.CoralogixConnectorAttributes, docsCoralogixConnector)
	inject(connectors.CriblConnectorAttributes, docsCriblConnector)
	inject(connectors.DarwiniumConnectorAttributes, docsDarwiniumConnector)
	inject(connectors.DatadogConnectorAttributes, docsDatadogConnector)
	inject(connectors.DevRevGrowConnectorAttributes, docsDevRevGrowConnector)
	inject(connectors.DoceboConnectorAttributes, docsDoceboConnector)
	inject(connectors.EightByEightViberConnectorAttributes, docsEightByEightViberConnector)
	inject(connectors.EightByEightWhatsappConnectorAttributes, docsEightByEightWhatsappConnector)
	inject(connectors.ElephantConnectorAttributes, docsElephantConnector)
	inject(connectors.ExternalTokenHTTPConnectorAttributes, docsExternalTokenHTTPConnector)
	inject(connectors.FingerprintConnectorAttributes, docsFingerprintConnector)
	inject(connectors.FingerprintDescopeConnectorAttributes, docsFingerprintDescopeConnector)
	inject(connectors.FirebaseAdminConnectorAttributes, docsFirebaseAdminConnector)
	inject(connectors.ForterConnectorAttributes, docsForterConnector)
	inject(connectors.GenericEmailGatewayConnectorAttributes, docsGenericEmailGatewayConnector)
	inject(connectors.GenericSMSGatewayConnectorAttributes, docsGenericSMSGatewayConnector)
	inject(connectors.GoogleCloudLoggingConnectorAttributes, docsGoogleCloudLoggingConnector)
	inject(connectors.GoogleCloudTranslationConnectorAttributes, docsGoogleCloudTranslationConnector)
	inject(connectors.GoogleMapsPlacesConnectorAttributes, docsGoogleMapsPlacesConnector)
	inject(connectors.GroundcoverConnectorAttributes, docsGroundcoverConnector)
	inject(connectors.HCaptchaConnectorAttributes, docsHCaptchaConnector)
	inject(connectors.HIBPConnectorAttributes, docsHIBPConnector)
	inject(connectors.HTTPConnectorAttributes, docsHTTPConnector)
	inject(connectors.HubSpotConnectorAttributes, docsHubSpotConnector)
	inject(connectors.IncodeConnectorAttributes, docsIncodeConnector)
	inject(connectors.IntercomConnectorAttributes, docsIntercomConnector)
	inject(connectors.LDAPConnectorAttributes, docsLDAPConnector)
	inject(connectors.LokaliseConnectorAttributes, docsLokaliseConnector)
	inject(connectors.MixpanelConnectorAttributes, docsMixpanelConnector)
	inject(connectors.MParticleConnectorAttributes, docsMParticleConnector)
	inject(connectors.NewRelicConnectorAttributes, docsNewRelicConnector)
	inject(connectors.OpenTelemetryConnectorAttributes, docsOpenTelemetryConnector)
	inject(connectors.PendoConnectorAttributes, docsPendoConnector)
	inject(connectors.PingDirectoryConnectorAttributes, docsPingDirectoryConnector)
	inject(connectors.PostmarkConnectorAttributes, docsPostmarkConnector)
	inject(connectors.RadarConnectorAttributes, docsRadarConnector)
	inject(connectors.RecaptchaConnectorAttributes, docsRecaptchaConnector)
	inject(connectors.RecaptchaEnterpriseConnectorAttributes, docsRecaptchaEnterpriseConnector)
	inject(connectors.RecaptchaV2ConnectorAttributes, docsRecaptchaV2Connector)
	inject(connectors.RekognitionConnectorAttributes, docsRekognitionConnector)
	inject(connectors.RndReassignedConnectorAttributes, docsRndReassignedConnector)
	inject(connectors.SalesforceConnectorAttributes, docsSalesforceConnector)
	inject(connectors.SalesforceMarketingCloudConnectorAttributes, docsSalesforceMarketingCloudConnector)
	inject(connectors.SardineConnectorAttributes, docsSardineConnector)
	inject(connectors.SCIMConnectorAttributes, docsSCIMConnector)
	inject(connectors.SegmentConnectorAttributes, docsSegmentConnector)
	inject(connectors.SendGridConnectorAttributes, docsSendGridConnector)
	inject(connectors.SESConnectorAttributes, docsSESConnector)
	inject(connectors.AuditFilterFieldAttributes, docsAuditFilterField)
	inject(connectors.HTTPAuthFieldAttributes, docsHTTPAuthField)
	inject(connectors.HTTPAuthBasicFieldAttributes, docsHTTPAuthBasicField)
	inject(connectors.HTTPAuthAPIKeyFieldAttributes, docsHTTPAuthAPIKeyField)
	inject(connectors.HTTPAuthOAuth2ClientCredentialsFieldAttributes, docsHTTPAuthOAuth2ClientCredentialsField)
	inject(connectors.SlackConnectorAttributes, docsSlackConnector)
	inject(connectors.SmartlingConnectorAttributes, docsSmartlingConnector)
	inject(connectors.SMTPConnectorAttributes, docsSMTPConnector)
	inject(connectors.SnowflakeConnectorAttributes, docsSnowflakeConnector)
	inject(connectors.SNSConnectorAttributes, docsSNSConnector)
	inject(connectors.SplunkConnectorAttributes, docsSplunkConnector)
	inject(connectors.SQLConnectorAttributes, docsSQLConnector)
	inject(connectors.SumoLogicConnectorAttributes, docsSumoLogicConnector)
	inject(connectors.SupabaseConnectorAttributes, docsSupabaseConnector)
	inject(connectors.TelesignConnectorAttributes, docsTelesignConnector)
	inject(connectors.TraceableConnectorAttributes, docsTraceableConnector)
	inject(connectors.TurnstileConnectorAttributes, docsTurnstileConnector)
	inject(connectors.TwilioCoreConnectorAttributes, docsTwilioCoreConnector)
	inject(connectors.TwilioVerifyConnectorAttributes, docsTwilioVerifyConnector)
	inject(connectors.UnibeamConnectorAttributes, docsUnibeamConnector)
	inject(connectors.ZeroBounceConnectorAttributes, docsZeroBounceConnector)
	inject(descoper.DescoperAttributes, docsDescoper)
	inject(descoper.DescoperProjectRoleAttributes, docsDescoperProjectRole)
	inject(descoper.RBacAttributes, docsRBac)
	inject(descoper.DescoperTagRoleAttributes, docsDescoperTagRole)
	inject(emailtemplate.EmailTemplateAttributes, docsEmailTemplate)
	inject(engine.EngineAttributes, docsEngine)
	inject(fgaschema.FGASchemaAttributes, docsFGASchema)
	inject(flow.FlowAttributes, docsFlow)
	inject(inboundapp.ApplicationScopeAttributes, docsApplicationScope)
	inject(inboundapp.InboundAppAttributes, docsInboundApp)
	inject(inboundapp.ScopeClaimMappingAttributes, docsScopeClaimMapping)
	inject(inboundapp.SessionSettingsAttributes, docsInboundappSessionSettings)
	inject(jwttemplate.JWTTemplateAttributes, docsJWTTemplate)
	inject(list.ListAttributes, docsList)
	inject(managementkey.ManagementKeyAttributes, docsManagementKey)
	inject(managementkey.ProjectRoleAttributes, docsProjectRole)
	inject(managementkey.ReBacAttributes, docsReBac)
	inject(managementkey.TagRoleAttributes, docsTagRole)
	inject(oauthprovider.ProviderAttributes, docsProvider)
	inject(oauthprovider.AppleKeyGeneratorModelAttributes, docsAppleKeyGeneratorModel)
	inject(outboundapp.OutboundAppAttributes, docsOutboundApp)
	inject(permission.PermissionAttributes, docsPermission)
	inject(project.ProjectAttributes, docsProject)
	inject(role.RoleAttributes, docsRole)
	inject(settings.AdminPortalAttributes, docsAdminPortal)
	inject(settings.AdminPortalWidgetAttributes, docsAdminPortalWidget)
	inject(settings.EmbeddedLinkSettingsAttributes, docsEmbeddedLinkSettings)
	inject(settings.EnchantedLinkSettingsAttributes, docsEnchantedLinkSettings)
	inject(settings.InviteSettingsAttributes, docsInviteSettings)
	inject(settings.MagicLinkSettingsAttributes, docsMagicLinkSettings)
	inject(settings.OAuthSettingsAttributes, docsOAuthSettings)
	inject(settings.OTPSettingsAttributes, docsOTPSettings)
	inject(settings.PasskeySettingsAttributes, docsPasskeySettings)
	inject(settings.PasswordSettingsAttributes, docsPasswordSettings)
	inject(settings.ProjectSettingsAttributes, docsProjectSettings)
	inject(settings.SessionSettingsAttributes, docsSettingsSessionSettings)
	inject(settings.SessionMigrationSettingsAttributes, docsSessionMigrationSettings)
	inject(settings.UserMappingItemAttributes, docsUserMappingItem)
	inject(settings.SSOSettingsAttributes, docsSSOSettings)
	inject(settings.MandatoryUserAttributeAttributes, docsMandatoryUserAttribute)
	inject(settings.SSOSuiteAttributes, docsSSOSuite)
	inject(settings.TOTPSettingsAttributes, docsTOTPSettings)
	inject(styles.StylesAttributes, docsStyles)
	inject(texttemplate.TextTemplateAttributes, docsTextTemplate)
	inject(voicetemplate.VoiceTemplateAttributes, docsVoiceTemplate)
	inject(widget.WidgetAttributes, docsWidget)
}

func inject(model map[string]schema.Attribute, docs map[string]string) {
	for field, desc := range docs {
		if _, found := model[field]; !found {
			panic(fmt.Sprintf("missing schema attribute for documentation key %s", field))
		}
		switch attr := model[field].(type) {
		case schema.StringAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.BoolAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.Int64Attribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.Float64Attribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.MapAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.ListAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.SetAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.MapNestedAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.SingleNestedAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.ListNestedAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.SetNestedAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		default:
			panic(fmt.Sprintf("unexpected schema type for documentation key %s: %T", field, attr))
		}
	}
}
