// Code generated by terragen. DO NOT EDIT.

package docs

import (
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/descoper"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/inboundapp"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/managementkey"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/project"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/project/adminportal"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/project/applications"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/project/attributes"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/project/authentication"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/project/authorization"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/project/connectors"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/project/flows"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/project/jwttemplates"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/project/lists"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/project/settings"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/project/templates"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/project/widgets"
)

func InjectModels() {
	inject(descoper.DescoperAttributes, docsDescoper)
	inject(descoper.DescoperProjectRoleAttributes, docsDescoperProjectRole)
	inject(descoper.RBacAttributes, docsRBac)
	inject(descoper.DescoperTagRoleAttributes, docsDescoperTagRole)
	inject(inboundapp.ApplicationScopeAttributes, docsApplicationScope)
	inject(inboundapp.InboundAppAttributes, docsInboundApp)
	inject(inboundapp.SessionSettingsAttributes, docsSessionSettings)
	inject(managementkey.ManagementKeyAttributes, docsManagementKey)
	inject(managementkey.ProjectRoleAttributes, docsProjectRole)
	inject(managementkey.ReBacAttributes, docsReBac)
	inject(managementkey.TagRoleAttributes, docsTagRole)
	inject(project.ProjectAttributes, docsProject)
	inject(adminportal.AdminPortalWidgetAttributes, docsAdminPortalWidget)
	inject(adminportal.AdminPortalAttributes, docsAdminPortal)
	inject(applications.ApplicationsAttributes, docsApplications)
	inject(applications.OIDCAttributes, docsOIDC)
	inject(applications.SAMLAttributes, docsSAML)
	inject(applications.AttributeMappingAttributes, docsAttributeMapping)
	inject(applications.DynamicConfigurationAttributes, docsDynamicConfiguration)
	inject(applications.ManualConfigurationAttributes, docsManualConfiguration)
	inject(attributes.AccessKeyAttributeAttributes, docsAccessKeyAttribute)
	inject(attributes.AccessKeyAttributeWidgetAuthorizationAttributes, docsAccessKeyAttributeWidgetAuthorization)
	inject(attributes.AttributesAttributes, docsAttributes)
	inject(attributes.TenantAttributeAttributes, docsTenantAttribute)
	inject(attributes.TenantAttributeAuthorizationAttributes, docsTenantAttributeAuthorization)
	inject(attributes.UserAttributeAttributes, docsUserAttribute)
	inject(attributes.UserAttributeWidgetAuthorizationAttributes, docsUserAttributeWidgetAuthorization)
	inject(authentication.AuthenticationAttributes, docsAuthentication)
	inject(authentication.EmbeddedLinkAttributes, docsEmbeddedLink)
	inject(authentication.EnchantedLinkAttributes, docsEnchantedLink)
	inject(authentication.MagicLinkAttributes, docsMagicLink)
	inject(authentication.OAuthAttributes, docsOAuth)
	inject(authentication.OAuthSystemProviderAttributes, docsOAuthSystemProvider)
	inject(authentication.OAuthProviderAttributes, docsOAuthProvider)
	inject(authentication.AppleKeyGeneratorModelAttributes, docsAppleKeyGeneratorModel)
	inject(authentication.OTPAttributes, docsOTP)
	inject(authentication.PasskeysAttributes, docsPasskeys)
	inject(authentication.PasswordAttributes, docsPassword)
	inject(authentication.SSOAttributes, docsSSO)
	inject(authentication.MandatoryUserAttributeAttributes, docsMandatoryUserAttribute)
	inject(authentication.SSOSuiteAttributes, docsSSOSuite)
	inject(authentication.TOTPAttributes, docsTOTP)
	inject(authorization.AuthorizationAttributes, docsAuthorization)
	inject(authorization.PermissionAttributes, docsPermission)
	inject(authorization.RoleAttributes, docsRole)
	inject(connectors.AbuseIPDBAttributes, docsAbuseIPDB)
	inject(connectors.AmplitudeAttributes, docsAmplitude)
	inject(connectors.ArkoseAttributes, docsArkose)
	inject(connectors.AuditWebhookAttributes, docsAuditWebhook)
	inject(connectors.AWSS3Attributes, docsAWSS3)
	inject(connectors.AWSTranslateAttributes, docsAWSTranslate)
	inject(connectors.BitsightAttributes, docsBitsight)
	inject(connectors.ConnectorsAttributes, docsConnectors)
	inject(connectors.CoralogixAttributes, docsCoralogix)
	inject(connectors.DarwiniumAttributes, docsDarwinium)
	inject(connectors.DatadogAttributes, docsDatadog)
	inject(connectors.DevRevGrowAttributes, docsDevRevGrow)
	inject(connectors.DoceboAttributes, docsDocebo)
	inject(connectors.EightByEightViberAttributes, docsEightByEightViber)
	inject(connectors.EightByEightWhatsappAttributes, docsEightByEightWhatsapp)
	inject(connectors.ElephantAttributes, docsElephant)
	inject(connectors.ExternalTokenHTTPAttributes, docsExternalTokenHTTP)
	inject(connectors.FingerprintAttributes, docsFingerprint)
	inject(connectors.FingerprintDescopeAttributes, docsFingerprintDescope)
	inject(connectors.FirebaseAdminAttributes, docsFirebaseAdmin)
	inject(connectors.ForterAttributes, docsForter)
	inject(connectors.GenericEmailGatewayAttributes, docsGenericEmailGateway)
	inject(connectors.GenericSMSGatewayAttributes, docsGenericSMSGateway)
	inject(connectors.GoogleCloudLoggingAttributes, docsGoogleCloudLogging)
	inject(connectors.GoogleCloudTranslationAttributes, docsGoogleCloudTranslation)
	inject(connectors.GoogleMapsPlacesAttributes, docsGoogleMapsPlaces)
	inject(connectors.HCaptchaAttributes, docsHCaptcha)
	inject(connectors.HIBPAttributes, docsHIBP)
	inject(connectors.HTTPAttributes, docsHTTP)
	inject(connectors.HubSpotAttributes, docsHubSpot)
	inject(connectors.IncodeAttributes, docsIncode)
	inject(connectors.IntercomAttributes, docsIntercom)
	inject(connectors.LDAPAttributes, docsLDAP)
	inject(connectors.LokaliseAttributes, docsLokalise)
	inject(connectors.MixpanelAttributes, docsMixpanel)
	inject(connectors.MParticleAttributes, docsMParticle)
	inject(connectors.NewRelicAttributes, docsNewRelic)
	inject(connectors.OpenTelemetryAttributes, docsOpenTelemetry)
	inject(connectors.PingDirectoryAttributes, docsPingDirectory)
	inject(connectors.PostmarkAttributes, docsPostmark)
	inject(connectors.RadarAttributes, docsRadar)
	inject(connectors.RecaptchaAttributes, docsRecaptcha)
	inject(connectors.RecaptchaEnterpriseAttributes, docsRecaptchaEnterprise)
	inject(connectors.RekognitionAttributes, docsRekognition)
	inject(connectors.SalesforceAttributes, docsSalesforce)
	inject(connectors.SalesforceMarketingCloudAttributes, docsSalesforceMarketingCloud)
	inject(connectors.SardineAttributes, docsSardine)
	inject(connectors.SegmentAttributes, docsSegment)
	inject(connectors.SendGridAttributes, docsSendGrid)
	inject(connectors.SendGridAuthFieldAttributes, docsSendGridAuthField)
	inject(connectors.SESAttributes, docsSES)
	inject(connectors.SenderFieldAttributes, docsSenderField)
	inject(connectors.ServerFieldAttributes, docsServerField)
	inject(connectors.AuditFilterFieldAttributes, docsAuditFilterField)
	inject(connectors.HTTPAuthFieldAttributes, docsHTTPAuthField)
	inject(connectors.HTTPAuthBasicFieldAttributes, docsHTTPAuthBasicField)
	inject(connectors.HTTPAuthAPIKeyFieldAttributes, docsHTTPAuthAPIKeyField)
	inject(connectors.SlackAttributes, docsSlack)
	inject(connectors.SmartlingAttributes, docsSmartling)
	inject(connectors.SMTPAttributes, docsSMTP)
	inject(connectors.SMTPAuthFieldAttributes, docsSMTPAuthField)
	inject(connectors.SNSAttributes, docsSNS)
	inject(connectors.SplunkAttributes, docsSplunk)
	inject(connectors.SQLAttributes, docsSQL)
	inject(connectors.SumoLogicAttributes, docsSumoLogic)
	inject(connectors.SupabaseAttributes, docsSupabase)
	inject(connectors.TelesignAttributes, docsTelesign)
	inject(connectors.TraceableAttributes, docsTraceable)
	inject(connectors.TurnstileAttributes, docsTurnstile)
	inject(connectors.TwilioCoreAttributes, docsTwilioCore)
	inject(connectors.TwilioCoreSendersFieldAttributes, docsTwilioCoreSendersField)
	inject(connectors.TwilioCoreSendersSMSFieldAttributes, docsTwilioCoreSendersSMSField)
	inject(connectors.TwilioCoreSendersVoiceFieldAttributes, docsTwilioCoreSendersVoiceField)
	inject(connectors.TwilioAuthFieldAttributes, docsTwilioAuthField)
	inject(connectors.TwilioVerifyAttributes, docsTwilioVerify)
	inject(connectors.UnibeamAttributes, docsUnibeam)
	inject(connectors.ZeroBounceAttributes, docsZeroBounce)
	inject(flows.FlowAttributes, docsFlow)
	inject(flows.StylesAttributes, docsStyles)
	inject(jwttemplates.JWTTemplateAttributes, docsJWTTemplate)
	inject(jwttemplates.JWTTemplatesAttributes, docsJWTTemplates)
	inject(lists.ListAttributes, docsList)
	inject(settings.InviteSettingsAttributes, docsInviteSettings)
	inject(settings.SessionMigrationAttributes, docsSessionMigration)
	inject(settings.SettingsAttributes, docsSettings)
	inject(templates.EmailServiceAttributes, docsEmailService)
	inject(templates.EmailTemplateAttributes, docsEmailTemplate)
	inject(templates.TextServiceAttributes, docsTextService)
	inject(templates.TextTemplateAttributes, docsTextTemplate)
	inject(templates.VoiceServiceAttributes, docsVoiceService)
	inject(templates.VoiceTemplateAttributes, docsVoiceTemplate)
	inject(widgets.WidgetAttributes, docsWidget)
}

func inject(model map[string]schema.Attribute, docs map[string]string) {
	for field, desc := range docs {
		if _, found := model[field]; !found {
			panic(fmt.Sprintf("missing schema attribute for documentation key %s", field))
		}
		switch attr := model[field].(type) {
		case schema.StringAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.BoolAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.Int64Attribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.Float64Attribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.MapAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.ListAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.SetAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.MapNestedAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.SingleNestedAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.ListNestedAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		case schema.SetNestedAttribute:
			attr.MarkdownDescription = desc
			model[field] = attr
		default:
			panic(fmt.Sprintf("unexpected schema type for documentation key %s: %T", field, attr))
		}
	}
}
