// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/helpers"
)

var AlloyAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"api_token":  stringattr.SecretRequired(),
	"api_secret": stringattr.SecretRequired(),
	"base_url":   stringattr.Required(),
}

// Model

type AlloyModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	APIToken  stringattr.Type `tfsdk:"api_token"`
	APISecret stringattr.Type `tfsdk:"api_secret"`
	BaseURL   stringattr.Type `tfsdk:"base_url"`
}

func (m *AlloyModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "alloy"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *AlloyModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *AlloyModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.APIToken, c, "apiToken")
	stringattr.Get(m.APISecret, c, "apiSecret")
	stringattr.Get(m.BaseURL, c, "baseUrl")
	return c
}

func (m *AlloyModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Nil(&m.APIToken)
	stringattr.Nil(&m.APISecret)
	stringattr.Set(&m.BaseURL, c, "baseUrl")
}

// Matching

func (m *AlloyModel) GetName() stringattr.Type {
	return m.Name
}

func (m *AlloyModel) GetID() stringattr.Type {
	return m.ID
}

func (m *AlloyModel) SetID(id stringattr.Type) {
	m.ID = id
}
