// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/helpers"
)

var ArkoseAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"public_key":      stringattr.Required(),
	"private_key":     stringattr.SecretRequired(),
	"client_base_url": stringattr.Default(""),
	"verify_base_url": stringattr.Default(""),
}

// Model

type ArkoseModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	PublicKey     stringattr.Type `tfsdk:"public_key"`
	PrivateKey    stringattr.Type `tfsdk:"private_key"`
	ClientBaseURL stringattr.Type `tfsdk:"client_base_url"`
	VerifyBaseURL stringattr.Type `tfsdk:"verify_base_url"`
}

func (m *ArkoseModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "arkose"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *ArkoseModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *ArkoseModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.PublicKey, c, "publicKey")
	stringattr.Get(m.PrivateKey, c, "privateKey")
	stringattr.Get(m.ClientBaseURL, c, "clientBaseUrl")
	stringattr.Get(m.VerifyBaseURL, c, "verifyBaseUrl")
	return c
}

func (m *ArkoseModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.PublicKey, c, "publicKey")
	stringattr.Nil(&m.PrivateKey)
	stringattr.Set(&m.ClientBaseURL, c, "clientBaseUrl")
	stringattr.Set(&m.VerifyBaseURL, c, "verifyBaseUrl")
}

// Matching

func (m *ArkoseModel) GetName() stringattr.Type {
	return m.Name
}

func (m *ArkoseModel) GetID() stringattr.Type {
	return m.ID
}

func (m *ArkoseModel) SetID(id stringattr.Type) {
	m.ID = id
}
