// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/helpers"
)

var AWSTranslateAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"access_key_id":     stringattr.Required(),
	"secret_access_key": stringattr.SecretRequired(),
	"session_token":     stringattr.SecretOptional(),
	"region":            stringattr.Required(),
}

// Model

type AWSTranslateModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	AccessKeyID     stringattr.Type `tfsdk:"access_key_id"`
	SecretAccessKey stringattr.Type `tfsdk:"secret_access_key"`
	SessionToken    stringattr.Type `tfsdk:"session_token"`
	Region          stringattr.Type `tfsdk:"region"`
}

func (m *AWSTranslateModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "aws-translate"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *AWSTranslateModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *AWSTranslateModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.AccessKeyID, c, "accessKeyId")
	stringattr.Get(m.SecretAccessKey, c, "secretAccessKey")
	stringattr.Get(m.SessionToken, c, "sessionToken")
	stringattr.Get(m.Region, c, "region")
	return c
}

func (m *AWSTranslateModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.AccessKeyID, c, "accessKeyId")
	stringattr.Nil(&m.SecretAccessKey)
	stringattr.Nil(&m.SessionToken)
	stringattr.Set(&m.Region, c, "region")
}

// Matching

func (m *AWSTranslateModel) GetName() stringattr.Type {
	return m.Name
}

func (m *AWSTranslateModel) GetID() stringattr.Type {
	return m.ID
}

func (m *AWSTranslateModel) SetID(id stringattr.Type) {
	m.ID = id
}
