// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/listattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/objattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/helpers"
)

var ConnectorsValidator = objattr.NewValidator[ConnectorsModel]("must have unique connector names")

var ConnectorsModifier = objattr.NewModifier[ConnectorsModel]("maintains connector identifiers between plan changes")

var ConnectorsAttributes = map[string]schema.Attribute{
	"abuseipdb":                  listattr.Default[AbuseIPDBModel](AbuseIPDBAttributes),
	"amplitude":                  listattr.Default[AmplitudeModel](AmplitudeAttributes),
	"arkose":                     listattr.Default[ArkoseModel](ArkoseAttributes),
	"audit_webhook":              listattr.Default[AuditWebhookModel](AuditWebhookAttributes),
	"aws_s3":                     listattr.Default[AWSS3Model](AWSS3Attributes, AWSS3Validator),
	"aws_translate":              listattr.Default[AWSTranslateModel](AWSTranslateAttributes),
	"bitsight":                   listattr.Default[BitsightModel](BitsightAttributes),
	"coralogix":                  listattr.Default[CoralogixModel](CoralogixAttributes, CoralogixValidator),
	"darwinium":                  listattr.Default[DarwiniumModel](DarwiniumAttributes),
	"datadog":                    listattr.Default[DatadogModel](DatadogAttributes, DatadogValidator),
	"devrev_grow":                listattr.Default[DevRevGrowModel](DevRevGrowAttributes),
	"docebo":                     listattr.Default[DoceboModel](DoceboAttributes),
	"eight_by_eight_viber":       listattr.Default[EightByEightViberModel](EightByEightViberAttributes),
	"eight_by_eight_whatsapp":    listattr.Default[EightByEightWhatsappModel](EightByEightWhatsappAttributes),
	"elephant":                   listattr.Default[ElephantModel](ElephantAttributes),
	"external_token_http":        listattr.Default[ExternalTokenHTTPModel](ExternalTokenHTTPAttributes),
	"fingerprint":                listattr.Default[FingerprintModel](FingerprintAttributes, FingerprintValidator),
	"fingerprint_descope":        listattr.Default[FingerprintDescopeModel](FingerprintDescopeAttributes),
	"firebase_admin":             listattr.Default[FirebaseAdminModel](FirebaseAdminAttributes),
	"forter":                     listattr.Default[ForterModel](ForterAttributes, ForterValidator),
	"generic_email_gateway":      listattr.Default[GenericEmailGatewayModel](GenericEmailGatewayAttributes),
	"generic_sms_gateway":        listattr.Default[GenericSMSGatewayModel](GenericSMSGatewayAttributes),
	"google_cloud_translation":   listattr.Default[GoogleCloudTranslationModel](GoogleCloudTranslationAttributes),
	"google_maps_places":         listattr.Default[GoogleMapsPlacesModel](GoogleMapsPlacesAttributes),
	"google_cloud_logging":       listattr.Default[GoogleCloudLoggingModel](GoogleCloudLoggingAttributes, GoogleCloudLoggingValidator),
	"hcaptcha":                   listattr.Default[HCaptchaModel](HCaptchaAttributes, HCaptchaValidator),
	"hibp":                       listattr.Default[HIBPModel](HIBPAttributes),
	"http":                       listattr.Default[HTTPModel](HTTPAttributes),
	"hubspot":                    listattr.Default[HubSpotModel](HubSpotAttributes),
	"incode":                     listattr.Default[IncodeModel](IncodeAttributes),
	"intercom":                   listattr.Default[IntercomModel](IntercomAttributes),
	"ldap":                       listattr.Default[LDAPModel](LDAPAttributes, LDAPValidator),
	"lokalise":                   listattr.Default[LokaliseModel](LokaliseAttributes),
	"mixpanel":                   listattr.Default[MixpanelModel](MixpanelAttributes, MixpanelValidator),
	"mparticle":                  listattr.Default[MParticleModel](MParticleAttributes),
	"newrelic":                   listattr.Default[NewRelicModel](NewRelicAttributes, NewRelicValidator),
	"opentelemetry":              listattr.Default[OpenTelemetryModel](OpenTelemetryAttributes, OpenTelemetryValidator),
	"ping_directory":             listattr.Default[PingDirectoryModel](PingDirectoryAttributes),
	"postmark":                   listattr.Default[PostmarkModel](PostmarkAttributes),
	"radar":                      listattr.Default[RadarModel](RadarAttributes),
	"recaptcha":                  listattr.Default[RecaptchaModel](RecaptchaAttributes, RecaptchaValidator),
	"recaptcha_enterprise":       listattr.Default[RecaptchaEnterpriseModel](RecaptchaEnterpriseAttributes, RecaptchaEnterpriseValidator),
	"rekognition":                listattr.Default[RekognitionModel](RekognitionAttributes),
	"salesforce":                 listattr.Default[SalesforceModel](SalesforceAttributes),
	"salesforce_marketing_cloud": listattr.Default[SalesforceMarketingCloudModel](SalesforceMarketingCloudAttributes),
	"sardine":                    listattr.Default[SardineModel](SardineAttributes),
	"segment":                    listattr.Default[SegmentModel](SegmentAttributes),
	"sendgrid":                   listattr.Default[SendGridModel](SendGridAttributes),
	"ses":                        listattr.Default[SESModel](SESAttributes, SESValidator),
	"slack":                      listattr.Default[SlackModel](SlackAttributes),
	"smartling":                  listattr.Default[SmartlingModel](SmartlingAttributes),
	"smtp":                       listattr.Default[SMTPModel](SMTPAttributes),
	"sns":                        listattr.Default[SNSModel](SNSAttributes, SNSValidator),
	"splunk":                     listattr.Default[SplunkModel](SplunkAttributes, SplunkValidator),
	"sql":                        listattr.Default[SQLModel](SQLAttributes, SQLValidator),
	"sumologic":                  listattr.Default[SumoLogicModel](SumoLogicAttributes, SumoLogicValidator),
	"supabase":                   listattr.Default[SupabaseModel](SupabaseAttributes, SupabaseValidator),
	"telesign":                   listattr.Default[TelesignModel](TelesignAttributes),
	"traceable":                  listattr.Default[TraceableModel](TraceableAttributes),
	"turnstile":                  listattr.Default[TurnstileModel](TurnstileAttributes),
	"twilio_core":                listattr.Default[TwilioCoreModel](TwilioCoreAttributes),
	"twilio_verify":              listattr.Default[TwilioVerifyModel](TwilioVerifyAttributes),
	"unibeam":                    listattr.Default[UnibeamModel](UnibeamAttributes),
	"zerobounce":                 listattr.Default[ZeroBounceModel](ZeroBounceAttributes),
}

type ConnectorsModel struct {
	AbuseIPDB                listattr.Type[AbuseIPDBModel]                `tfsdk:"abuseipdb"`
	Amplitude                listattr.Type[AmplitudeModel]                `tfsdk:"amplitude"`
	Arkose                   listattr.Type[ArkoseModel]                   `tfsdk:"arkose"`
	AuditWebhook             listattr.Type[AuditWebhookModel]             `tfsdk:"audit_webhook"`
	AWSS3                    listattr.Type[AWSS3Model]                    `tfsdk:"aws_s3"`
	AWSTranslate             listattr.Type[AWSTranslateModel]             `tfsdk:"aws_translate"`
	Bitsight                 listattr.Type[BitsightModel]                 `tfsdk:"bitsight"`
	Coralogix                listattr.Type[CoralogixModel]                `tfsdk:"coralogix"`
	Darwinium                listattr.Type[DarwiniumModel]                `tfsdk:"darwinium"`
	Datadog                  listattr.Type[DatadogModel]                  `tfsdk:"datadog"`
	DevRevGrow               listattr.Type[DevRevGrowModel]               `tfsdk:"devrev_grow"`
	Docebo                   listattr.Type[DoceboModel]                   `tfsdk:"docebo"`
	EightByEightViber        listattr.Type[EightByEightViberModel]        `tfsdk:"eight_by_eight_viber"`
	EightByEightWhatsapp     listattr.Type[EightByEightWhatsappModel]     `tfsdk:"eight_by_eight_whatsapp"`
	Elephant                 listattr.Type[ElephantModel]                 `tfsdk:"elephant"`
	ExternalTokenHTTP        listattr.Type[ExternalTokenHTTPModel]        `tfsdk:"external_token_http"`
	Fingerprint              listattr.Type[FingerprintModel]              `tfsdk:"fingerprint"`
	FingerprintDescope       listattr.Type[FingerprintDescopeModel]       `tfsdk:"fingerprint_descope"`
	FirebaseAdmin            listattr.Type[FirebaseAdminModel]            `tfsdk:"firebase_admin"`
	Forter                   listattr.Type[ForterModel]                   `tfsdk:"forter"`
	GenericEmailGateway      listattr.Type[GenericEmailGatewayModel]      `tfsdk:"generic_email_gateway"`
	GenericSMSGateway        listattr.Type[GenericSMSGatewayModel]        `tfsdk:"generic_sms_gateway"`
	GoogleCloudTranslation   listattr.Type[GoogleCloudTranslationModel]   `tfsdk:"google_cloud_translation"`
	GoogleMapsPlaces         listattr.Type[GoogleMapsPlacesModel]         `tfsdk:"google_maps_places"`
	GoogleCloudLogging       listattr.Type[GoogleCloudLoggingModel]       `tfsdk:"google_cloud_logging"`
	HCaptcha                 listattr.Type[HCaptchaModel]                 `tfsdk:"hcaptcha"`
	HIBP                     listattr.Type[HIBPModel]                     `tfsdk:"hibp"`
	HTTP                     listattr.Type[HTTPModel]                     `tfsdk:"http"`
	HubSpot                  listattr.Type[HubSpotModel]                  `tfsdk:"hubspot"`
	Incode                   listattr.Type[IncodeModel]                   `tfsdk:"incode"`
	Intercom                 listattr.Type[IntercomModel]                 `tfsdk:"intercom"`
	LDAP                     listattr.Type[LDAPModel]                     `tfsdk:"ldap"`
	Lokalise                 listattr.Type[LokaliseModel]                 `tfsdk:"lokalise"`
	Mixpanel                 listattr.Type[MixpanelModel]                 `tfsdk:"mixpanel"`
	MParticle                listattr.Type[MParticleModel]                `tfsdk:"mparticle"`
	NewRelic                 listattr.Type[NewRelicModel]                 `tfsdk:"newrelic"`
	OpenTelemetry            listattr.Type[OpenTelemetryModel]            `tfsdk:"opentelemetry"`
	PingDirectory            listattr.Type[PingDirectoryModel]            `tfsdk:"ping_directory"`
	Postmark                 listattr.Type[PostmarkModel]                 `tfsdk:"postmark"`
	Radar                    listattr.Type[RadarModel]                    `tfsdk:"radar"`
	Recaptcha                listattr.Type[RecaptchaModel]                `tfsdk:"recaptcha"`
	RecaptchaEnterprise      listattr.Type[RecaptchaEnterpriseModel]      `tfsdk:"recaptcha_enterprise"`
	Rekognition              listattr.Type[RekognitionModel]              `tfsdk:"rekognition"`
	Salesforce               listattr.Type[SalesforceModel]               `tfsdk:"salesforce"`
	SalesforceMarketingCloud listattr.Type[SalesforceMarketingCloudModel] `tfsdk:"salesforce_marketing_cloud"`
	Sardine                  listattr.Type[SardineModel]                  `tfsdk:"sardine"`
	Segment                  listattr.Type[SegmentModel]                  `tfsdk:"segment"`
	SendGrid                 listattr.Type[SendGridModel]                 `tfsdk:"sendgrid"`
	SES                      listattr.Type[SESModel]                      `tfsdk:"ses"`
	Slack                    listattr.Type[SlackModel]                    `tfsdk:"slack"`
	Smartling                listattr.Type[SmartlingModel]                `tfsdk:"smartling"`
	SMTP                     listattr.Type[SMTPModel]                     `tfsdk:"smtp"`
	SNS                      listattr.Type[SNSModel]                      `tfsdk:"sns"`
	Splunk                   listattr.Type[SplunkModel]                   `tfsdk:"splunk"`
	SQL                      listattr.Type[SQLModel]                      `tfsdk:"sql"`
	SumoLogic                listattr.Type[SumoLogicModel]                `tfsdk:"sumologic"`
	Supabase                 listattr.Type[SupabaseModel]                 `tfsdk:"supabase"`
	Telesign                 listattr.Type[TelesignModel]                 `tfsdk:"telesign"`
	Traceable                listattr.Type[TraceableModel]                `tfsdk:"traceable"`
	Turnstile                listattr.Type[TurnstileModel]                `tfsdk:"turnstile"`
	TwilioCore               listattr.Type[TwilioCoreModel]               `tfsdk:"twilio_core"`
	TwilioVerify             listattr.Type[TwilioVerifyModel]             `tfsdk:"twilio_verify"`
	Unibeam                  listattr.Type[UnibeamModel]                  `tfsdk:"unibeam"`
	ZeroBounce               listattr.Type[ZeroBounceModel]               `tfsdk:"zerobounce"`
}

func (m *ConnectorsModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	listattr.Get(m.AbuseIPDB, data, "abuseipdb", h)
	listattr.Get(m.Amplitude, data, "amplitude", h)
	listattr.Get(m.Arkose, data, "arkose", h)
	listattr.Get(m.AuditWebhook, data, "audit-webhook", h)
	listattr.Get(m.AWSS3, data, "aws-s3", h)
	listattr.Get(m.AWSTranslate, data, "aws-translate", h)
	listattr.Get(m.Bitsight, data, "bitsight", h)
	listattr.Get(m.Coralogix, data, "coralogix", h)
	listattr.Get(m.Darwinium, data, "darwinium", h)
	listattr.Get(m.Datadog, data, "datadog", h)
	listattr.Get(m.DevRevGrow, data, "devrev-grow", h)
	listattr.Get(m.Docebo, data, "docebo", h)
	listattr.Get(m.EightByEightViber, data, "eight-by-eight-viber", h)
	listattr.Get(m.EightByEightWhatsapp, data, "eight-by-eight-whatsapp", h)
	listattr.Get(m.Elephant, data, "elephant", h)
	listattr.Get(m.ExternalTokenHTTP, data, "external-token-http", h)
	listattr.Get(m.Fingerprint, data, "fingerprint", h)
	listattr.Get(m.FingerprintDescope, data, "fingerprint-descope", h)
	listattr.Get(m.FirebaseAdmin, data, "firebase-admin", h)
	listattr.Get(m.Forter, data, "forter", h)
	listattr.Get(m.GenericEmailGateway, data, "generic-email-gateway", h)
	listattr.Get(m.GenericSMSGateway, data, "generic-sms-gateway", h)
	listattr.Get(m.GoogleCloudTranslation, data, "google-cloud-translation", h)
	listattr.Get(m.GoogleMapsPlaces, data, "google-maps-places", h)
	listattr.Get(m.GoogleCloudLogging, data, "googlecloudlogging", h)
	listattr.Get(m.HCaptcha, data, "hcaptcha", h)
	listattr.Get(m.HIBP, data, "hibp", h)
	listattr.Get(m.HTTP, data, "http", h)
	listattr.Get(m.HubSpot, data, "hubspot", h)
	listattr.Get(m.Incode, data, "incode", h)
	listattr.Get(m.Intercom, data, "intercom", h)
	listattr.Get(m.LDAP, data, "ldap", h)
	listattr.Get(m.Lokalise, data, "lokalise", h)
	listattr.Get(m.Mixpanel, data, "mixpanel", h)
	listattr.Get(m.MParticle, data, "mparticle", h)
	listattr.Get(m.NewRelic, data, "newrelic", h)
	listattr.Get(m.OpenTelemetry, data, "opentelemetry", h)
	listattr.Get(m.PingDirectory, data, "ping-directory", h)
	listattr.Get(m.Postmark, data, "post-mark", h)
	listattr.Get(m.Radar, data, "radar", h)
	listattr.Get(m.Recaptcha, data, "recaptcha", h)
	listattr.Get(m.RecaptchaEnterprise, data, "recaptcha-enterprise", h)
	listattr.Get(m.Rekognition, data, "rekognition", h)
	listattr.Get(m.Salesforce, data, "salesforce", h)
	listattr.Get(m.SalesforceMarketingCloud, data, "salesforce-marketing-cloud", h)
	listattr.Get(m.Sardine, data, "sardine", h)
	listattr.Get(m.Segment, data, "segment", h)
	listattr.Get(m.SendGrid, data, "sendgrid", h)
	listattr.Get(m.SES, data, "ses", h)
	listattr.Get(m.Slack, data, "slack", h)
	listattr.Get(m.Smartling, data, "smartling", h)
	listattr.Get(m.SMTP, data, "smtp", h)
	listattr.Get(m.SNS, data, "sns", h)
	listattr.Get(m.Splunk, data, "splunk", h)
	listattr.Get(m.SQL, data, "sql", h)
	listattr.Get(m.SumoLogic, data, "sumologic", h)
	listattr.Get(m.Supabase, data, "supabase", h)
	listattr.Get(m.Telesign, data, "telesign", h)
	listattr.Get(m.Traceable, data, "traceable", h)
	listattr.Get(m.Turnstile, data, "turnstile", h)
	listattr.Get(m.TwilioCore, data, "twilio-core", h)
	listattr.Get(m.TwilioVerify, data, "twilio-verify", h)
	listattr.Get(m.Unibeam, data, "unibeam", h)
	listattr.Get(m.ZeroBounce, data, "zerobounce", h)
	return data
}

func (m *ConnectorsModel) SetValues(h *helpers.Handler, data map[string]any) {
	listattr.SetMatchingNames(&m.AbuseIPDB, data, "abuseipdb", "name", h)
	listattr.SetMatchingNames(&m.Amplitude, data, "amplitude", "name", h)
	listattr.SetMatchingNames(&m.Arkose, data, "arkose", "name", h)
	listattr.SetMatchingNames(&m.AuditWebhook, data, "audit-webhook", "name", h)
	listattr.SetMatchingNames(&m.AWSS3, data, "aws-s3", "name", h)
	listattr.SetMatchingNames(&m.AWSTranslate, data, "aws-translate", "name", h)
	listattr.SetMatchingNames(&m.Bitsight, data, "bitsight", "name", h)
	listattr.SetMatchingNames(&m.Coralogix, data, "coralogix", "name", h)
	listattr.SetMatchingNames(&m.Darwinium, data, "darwinium", "name", h)
	listattr.SetMatchingNames(&m.Datadog, data, "datadog", "name", h)
	listattr.SetMatchingNames(&m.DevRevGrow, data, "devrev-grow", "name", h)
	listattr.SetMatchingNames(&m.Docebo, data, "docebo", "name", h)
	listattr.SetMatchingNames(&m.EightByEightViber, data, "eight-by-eight-viber", "name", h)
	listattr.SetMatchingNames(&m.EightByEightWhatsapp, data, "eight-by-eight-whatsapp", "name", h)
	listattr.SetMatchingNames(&m.Elephant, data, "elephant", "name", h)
	listattr.SetMatchingNames(&m.ExternalTokenHTTP, data, "external-token-http", "name", h)
	listattr.SetMatchingNames(&m.Fingerprint, data, "fingerprint", "name", h)
	listattr.SetMatchingNames(&m.FingerprintDescope, data, "fingerprint-descope", "name", h)
	listattr.SetMatchingNames(&m.FirebaseAdmin, data, "firebase-admin", "name", h)
	listattr.SetMatchingNames(&m.Forter, data, "forter", "name", h)
	listattr.SetMatchingNames(&m.GenericEmailGateway, data, "generic-email-gateway", "name", h)
	listattr.SetMatchingNames(&m.GenericSMSGateway, data, "generic-sms-gateway", "name", h)
	listattr.SetMatchingNames(&m.GoogleCloudTranslation, data, "google-cloud-translation", "name", h)
	listattr.SetMatchingNames(&m.GoogleMapsPlaces, data, "google-maps-places", "name", h)
	listattr.SetMatchingNames(&m.GoogleCloudLogging, data, "googlecloudlogging", "name", h)
	listattr.SetMatchingNames(&m.HCaptcha, data, "hcaptcha", "name", h)
	listattr.SetMatchingNames(&m.HIBP, data, "hibp", "name", h)
	listattr.SetMatchingNames(&m.HTTP, data, "http", "name", h)
	listattr.SetMatchingNames(&m.HubSpot, data, "hubspot", "name", h)
	listattr.SetMatchingNames(&m.Incode, data, "incode", "name", h)
	listattr.SetMatchingNames(&m.Intercom, data, "intercom", "name", h)
	listattr.SetMatchingNames(&m.LDAP, data, "ldap", "name", h)
	listattr.SetMatchingNames(&m.Lokalise, data, "lokalise", "name", h)
	listattr.SetMatchingNames(&m.Mixpanel, data, "mixpanel", "name", h)
	listattr.SetMatchingNames(&m.MParticle, data, "mparticle", "name", h)
	listattr.SetMatchingNames(&m.NewRelic, data, "newrelic", "name", h)
	listattr.SetMatchingNames(&m.OpenTelemetry, data, "opentelemetry", "name", h)
	listattr.SetMatchingNames(&m.PingDirectory, data, "ping-directory", "name", h)
	listattr.SetMatchingNames(&m.Postmark, data, "post-mark", "name", h)
	listattr.SetMatchingNames(&m.Radar, data, "radar", "name", h)
	listattr.SetMatchingNames(&m.Recaptcha, data, "recaptcha", "name", h)
	listattr.SetMatchingNames(&m.RecaptchaEnterprise, data, "recaptcha-enterprise", "name", h)
	listattr.SetMatchingNames(&m.Rekognition, data, "rekognition", "name", h)
	listattr.SetMatchingNames(&m.Salesforce, data, "salesforce", "name", h)
	listattr.SetMatchingNames(&m.SalesforceMarketingCloud, data, "salesforce-marketing-cloud", "name", h)
	listattr.SetMatchingNames(&m.Sardine, data, "sardine", "name", h)
	listattr.SetMatchingNames(&m.Segment, data, "segment", "name", h)
	listattr.SetMatchingNames(&m.SendGrid, data, "sendgrid", "name", h)
	listattr.SetMatchingNames(&m.SES, data, "ses", "name", h)
	listattr.SetMatchingNames(&m.Slack, data, "slack", "name", h)
	listattr.SetMatchingNames(&m.Smartling, data, "smartling", "name", h)
	listattr.SetMatchingNames(&m.SMTP, data, "smtp", "name", h)
	listattr.SetMatchingNames(&m.SNS, data, "sns", "name", h)
	listattr.SetMatchingNames(&m.Splunk, data, "splunk", "name", h)
	listattr.SetMatchingNames(&m.SQL, data, "sql", "name", h)
	listattr.SetMatchingNames(&m.SumoLogic, data, "sumologic", "name", h)
	listattr.SetMatchingNames(&m.Supabase, data, "supabase", "name", h)
	listattr.SetMatchingNames(&m.Telesign, data, "telesign", "name", h)
	listattr.SetMatchingNames(&m.Traceable, data, "traceable", "name", h)
	listattr.SetMatchingNames(&m.Turnstile, data, "turnstile", "name", h)
	listattr.SetMatchingNames(&m.TwilioCore, data, "twilio-core", "name", h)
	listattr.SetMatchingNames(&m.TwilioVerify, data, "twilio-verify", "name", h)
	listattr.SetMatchingNames(&m.Unibeam, data, "unibeam", "name", h)
	listattr.SetMatchingNames(&m.ZeroBounce, data, "zerobounce", "name", h)
}

func (m *ConnectorsModel) CollectReferences(h *helpers.Handler) {
	addConnectorReferences(h, "abuseipdb", m.AbuseIPDB)
	addConnectorReferences(h, "amplitude", m.Amplitude)
	addConnectorReferences(h, "arkose", m.Arkose)
	addConnectorReferences(h, "audit-webhook", m.AuditWebhook)
	addConnectorReferences(h, "aws-s3", m.AWSS3)
	addConnectorReferences(h, "aws-translate", m.AWSTranslate)
	addConnectorReferences(h, "bitsight", m.Bitsight)
	addConnectorReferences(h, "coralogix", m.Coralogix)
	addConnectorReferences(h, "darwinium", m.Darwinium)
	addConnectorReferences(h, "datadog", m.Datadog)
	addConnectorReferences(h, "devrev-grow", m.DevRevGrow)
	addConnectorReferences(h, "docebo", m.Docebo)
	addConnectorReferences(h, "eight-by-eight-viber", m.EightByEightViber)
	addConnectorReferences(h, "eight-by-eight-whatsapp", m.EightByEightWhatsapp)
	addConnectorReferences(h, "elephant", m.Elephant)
	addConnectorReferences(h, "external-token-http", m.ExternalTokenHTTP)
	addConnectorReferences(h, "fingerprint", m.Fingerprint)
	addConnectorReferences(h, "fingerprint-descope", m.FingerprintDescope)
	addConnectorReferences(h, "firebase-admin", m.FirebaseAdmin)
	addConnectorReferences(h, "forter", m.Forter)
	addConnectorReferences(h, "generic-email-gateway", m.GenericEmailGateway)
	addConnectorReferences(h, "generic-sms-gateway", m.GenericSMSGateway)
	addConnectorReferences(h, "google-cloud-translation", m.GoogleCloudTranslation)
	addConnectorReferences(h, "google-maps-places", m.GoogleMapsPlaces)
	addConnectorReferences(h, "googlecloudlogging", m.GoogleCloudLogging)
	addConnectorReferences(h, "hcaptcha", m.HCaptcha)
	addConnectorReferences(h, "hibp", m.HIBP)
	addConnectorReferences(h, "http", m.HTTP)
	addConnectorReferences(h, "hubspot", m.HubSpot)
	addConnectorReferences(h, "incode", m.Incode)
	addConnectorReferences(h, "intercom", m.Intercom)
	addConnectorReferences(h, "ldap", m.LDAP)
	addConnectorReferences(h, "lokalise", m.Lokalise)
	addConnectorReferences(h, "mixpanel", m.Mixpanel)
	addConnectorReferences(h, "mparticle", m.MParticle)
	addConnectorReferences(h, "newrelic", m.NewRelic)
	addConnectorReferences(h, "opentelemetry", m.OpenTelemetry)
	addConnectorReferences(h, "ping-directory", m.PingDirectory)
	addConnectorReferences(h, "post-mark", m.Postmark)
	addConnectorReferences(h, "radar", m.Radar)
	addConnectorReferences(h, "recaptcha", m.Recaptcha)
	addConnectorReferences(h, "recaptcha-enterprise", m.RecaptchaEnterprise)
	addConnectorReferences(h, "rekognition", m.Rekognition)
	addConnectorReferences(h, "salesforce", m.Salesforce)
	addConnectorReferences(h, "salesforce-marketing-cloud", m.SalesforceMarketingCloud)
	addConnectorReferences(h, "sardine", m.Sardine)
	addConnectorReferences(h, "segment", m.Segment)
	addConnectorReferences(h, "sendgrid", m.SendGrid)
	addConnectorReferences(h, "ses", m.SES)
	addConnectorReferences(h, "slack", m.Slack)
	addConnectorReferences(h, "smartling", m.Smartling)
	addConnectorReferences(h, "smtp", m.SMTP)
	addConnectorReferences(h, "sns", m.SNS)
	addConnectorReferences(h, "splunk", m.Splunk)
	addConnectorReferences(h, "sql", m.SQL)
	addConnectorReferences(h, "sumologic", m.SumoLogic)
	addConnectorReferences(h, "supabase", m.Supabase)
	addConnectorReferences(h, "telesign", m.Telesign)
	addConnectorReferences(h, "traceable", m.Traceable)
	addConnectorReferences(h, "turnstile", m.Turnstile)
	addConnectorReferences(h, "twilio-core", m.TwilioCore)
	addConnectorReferences(h, "twilio-verify", m.TwilioVerify)
	addConnectorReferences(h, "unibeam", m.Unibeam)
	addConnectorReferences(h, "zerobounce", m.ZeroBounce)
}

func (m *ConnectorsModel) Validate(h *helpers.Handler) {
	names := map[string]int{}
	addConnectorNames(h, names, m.AbuseIPDB)
	addConnectorNames(h, names, m.Amplitude)
	addConnectorNames(h, names, m.Arkose)
	addConnectorNames(h, names, m.AuditWebhook)
	addConnectorNames(h, names, m.AWSS3)
	addConnectorNames(h, names, m.AWSTranslate)
	addConnectorNames(h, names, m.Bitsight)
	addConnectorNames(h, names, m.Coralogix)
	addConnectorNames(h, names, m.Darwinium)
	addConnectorNames(h, names, m.Datadog)
	addConnectorNames(h, names, m.DevRevGrow)
	addConnectorNames(h, names, m.Docebo)
	addConnectorNames(h, names, m.EightByEightViber)
	addConnectorNames(h, names, m.EightByEightWhatsapp)
	addConnectorNames(h, names, m.Elephant)
	addConnectorNames(h, names, m.ExternalTokenHTTP)
	addConnectorNames(h, names, m.Fingerprint)
	addConnectorNames(h, names, m.FingerprintDescope)
	addConnectorNames(h, names, m.FirebaseAdmin)
	addConnectorNames(h, names, m.Forter)
	addConnectorNames(h, names, m.GenericEmailGateway)
	addConnectorNames(h, names, m.GenericSMSGateway)
	addConnectorNames(h, names, m.GoogleCloudTranslation)
	addConnectorNames(h, names, m.GoogleMapsPlaces)
	addConnectorNames(h, names, m.GoogleCloudLogging)
	addConnectorNames(h, names, m.HCaptcha)
	addConnectorNames(h, names, m.HIBP)
	addConnectorNames(h, names, m.HTTP)
	addConnectorNames(h, names, m.HubSpot)
	addConnectorNames(h, names, m.Incode)
	addConnectorNames(h, names, m.Intercom)
	addConnectorNames(h, names, m.LDAP)
	addConnectorNames(h, names, m.Lokalise)
	addConnectorNames(h, names, m.Mixpanel)
	addConnectorNames(h, names, m.MParticle)
	addConnectorNames(h, names, m.NewRelic)
	addConnectorNames(h, names, m.OpenTelemetry)
	addConnectorNames(h, names, m.PingDirectory)
	addConnectorNames(h, names, m.Postmark)
	addConnectorNames(h, names, m.Radar)
	addConnectorNames(h, names, m.Recaptcha)
	addConnectorNames(h, names, m.RecaptchaEnterprise)
	addConnectorNames(h, names, m.Rekognition)
	addConnectorNames(h, names, m.Salesforce)
	addConnectorNames(h, names, m.SalesforceMarketingCloud)
	addConnectorNames(h, names, m.Sardine)
	addConnectorNames(h, names, m.Segment)
	addConnectorNames(h, names, m.SendGrid)
	addConnectorNames(h, names, m.SES)
	addConnectorNames(h, names, m.Slack)
	addConnectorNames(h, names, m.Smartling)
	addConnectorNames(h, names, m.SMTP)
	addConnectorNames(h, names, m.SNS)
	addConnectorNames(h, names, m.Splunk)
	addConnectorNames(h, names, m.SQL)
	addConnectorNames(h, names, m.SumoLogic)
	addConnectorNames(h, names, m.Supabase)
	addConnectorNames(h, names, m.Telesign)
	addConnectorNames(h, names, m.Traceable)
	addConnectorNames(h, names, m.Turnstile)
	addConnectorNames(h, names, m.TwilioCore)
	addConnectorNames(h, names, m.TwilioVerify)
	addConnectorNames(h, names, m.Unibeam)
	addConnectorNames(h, names, m.ZeroBounce)
	for k, v := range names {
		if v > 1 {
			h.Error("Connector names must be unique", "The connector name '%s' is used %d times", k, v)
		}
	}
}

func (m *ConnectorsModel) Modify(h *helpers.Handler, state *ConnectorsModel) {
	listattr.ModifyMatchingNames(h, &m.AbuseIPDB, state.AbuseIPDB)
	listattr.ModifyMatchingNames(h, &m.Amplitude, state.Amplitude)
	listattr.ModifyMatchingNames(h, &m.Arkose, state.Arkose)
	listattr.ModifyMatchingNames(h, &m.AuditWebhook, state.AuditWebhook)
	listattr.ModifyMatchingNames(h, &m.AWSS3, state.AWSS3)
	listattr.ModifyMatchingNames(h, &m.AWSTranslate, state.AWSTranslate)
	listattr.ModifyMatchingNames(h, &m.Bitsight, state.Bitsight)
	listattr.ModifyMatchingNames(h, &m.Coralogix, state.Coralogix)
	listattr.ModifyMatchingNames(h, &m.Darwinium, state.Darwinium)
	listattr.ModifyMatchingNames(h, &m.Datadog, state.Datadog)
	listattr.ModifyMatchingNames(h, &m.DevRevGrow, state.DevRevGrow)
	listattr.ModifyMatchingNames(h, &m.Docebo, state.Docebo)
	listattr.ModifyMatchingNames(h, &m.EightByEightViber, state.EightByEightViber)
	listattr.ModifyMatchingNames(h, &m.EightByEightWhatsapp, state.EightByEightWhatsapp)
	listattr.ModifyMatchingNames(h, &m.Elephant, state.Elephant)
	listattr.ModifyMatchingNames(h, &m.ExternalTokenHTTP, state.ExternalTokenHTTP)
	listattr.ModifyMatchingNames(h, &m.Fingerprint, state.Fingerprint)
	listattr.ModifyMatchingNames(h, &m.FingerprintDescope, state.FingerprintDescope)
	listattr.ModifyMatchingNames(h, &m.FirebaseAdmin, state.FirebaseAdmin)
	listattr.ModifyMatchingNames(h, &m.Forter, state.Forter)
	listattr.ModifyMatchingNames(h, &m.GenericEmailGateway, state.GenericEmailGateway)
	listattr.ModifyMatchingNames(h, &m.GenericSMSGateway, state.GenericSMSGateway)
	listattr.ModifyMatchingNames(h, &m.GoogleCloudTranslation, state.GoogleCloudTranslation)
	listattr.ModifyMatchingNames(h, &m.GoogleMapsPlaces, state.GoogleMapsPlaces)
	listattr.ModifyMatchingNames(h, &m.GoogleCloudLogging, state.GoogleCloudLogging)
	listattr.ModifyMatchingNames(h, &m.HCaptcha, state.HCaptcha)
	listattr.ModifyMatchingNames(h, &m.HIBP, state.HIBP)
	listattr.ModifyMatchingNames(h, &m.HTTP, state.HTTP)
	listattr.ModifyMatchingNames(h, &m.HubSpot, state.HubSpot)
	listattr.ModifyMatchingNames(h, &m.Incode, state.Incode)
	listattr.ModifyMatchingNames(h, &m.Intercom, state.Intercom)
	listattr.ModifyMatchingNames(h, &m.LDAP, state.LDAP)
	listattr.ModifyMatchingNames(h, &m.Lokalise, state.Lokalise)
	listattr.ModifyMatchingNames(h, &m.Mixpanel, state.Mixpanel)
	listattr.ModifyMatchingNames(h, &m.MParticle, state.MParticle)
	listattr.ModifyMatchingNames(h, &m.NewRelic, state.NewRelic)
	listattr.ModifyMatchingNames(h, &m.OpenTelemetry, state.OpenTelemetry)
	listattr.ModifyMatchingNames(h, &m.PingDirectory, state.PingDirectory)
	listattr.ModifyMatchingNames(h, &m.Postmark, state.Postmark)
	listattr.ModifyMatchingNames(h, &m.Radar, state.Radar)
	listattr.ModifyMatchingNames(h, &m.Recaptcha, state.Recaptcha)
	listattr.ModifyMatchingNames(h, &m.RecaptchaEnterprise, state.RecaptchaEnterprise)
	listattr.ModifyMatchingNames(h, &m.Rekognition, state.Rekognition)
	listattr.ModifyMatchingNames(h, &m.Salesforce, state.Salesforce)
	listattr.ModifyMatchingNames(h, &m.SalesforceMarketingCloud, state.SalesforceMarketingCloud)
	listattr.ModifyMatchingNames(h, &m.Sardine, state.Sardine)
	listattr.ModifyMatchingNames(h, &m.Segment, state.Segment)
	listattr.ModifyMatchingNames(h, &m.SendGrid, state.SendGrid)
	listattr.ModifyMatchingNames(h, &m.SES, state.SES)
	listattr.ModifyMatchingNames(h, &m.Slack, state.Slack)
	listattr.ModifyMatchingNames(h, &m.Smartling, state.Smartling)
	listattr.ModifyMatchingNames(h, &m.SMTP, state.SMTP)
	listattr.ModifyMatchingNames(h, &m.SNS, state.SNS)
	listattr.ModifyMatchingNames(h, &m.Splunk, state.Splunk)
	listattr.ModifyMatchingNames(h, &m.SQL, state.SQL)
	listattr.ModifyMatchingNames(h, &m.SumoLogic, state.SumoLogic)
	listattr.ModifyMatchingNames(h, &m.Supabase, state.Supabase)
	listattr.ModifyMatchingNames(h, &m.Telesign, state.Telesign)
	listattr.ModifyMatchingNames(h, &m.Traceable, state.Traceable)
	listattr.ModifyMatchingNames(h, &m.Turnstile, state.Turnstile)
	listattr.ModifyMatchingNames(h, &m.TwilioCore, state.TwilioCore)
	listattr.ModifyMatchingNames(h, &m.TwilioVerify, state.TwilioVerify)
	listattr.ModifyMatchingNames(h, &m.Unibeam, state.Unibeam)
	listattr.ModifyMatchingNames(h, &m.ZeroBounce, state.ZeroBounce)

	// Upgrade existing identifiers for SMTP connectors to support static IPs
	for c := range listattr.MutatingIterator(&m.SMTP, h) {
		id := c.ID.ValueString()
		if v := strings.TrimPrefix(id, "MP"); v != id && c.UseStaticIPs.ValueBool() {
			c.ID = stringattr.Value("CI" + v)
			h.Log("Upgrading identifier for SMTP connector from '%s' to '%s'", id, c.ID.ValueString())
		}
	}
}
