// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/boolattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/listattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/objattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/helpers"
)

var CoralogixValidator = objattr.NewValidator[CoralogixModel]("must have a valid configuration")

var CoralogixAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"endpoint":                 stringattr.Required(),
	"bearer_token":             stringattr.SecretRequired(),
	"audit_enabled":            boolattr.Default(true),
	"audit_filters":            listattr.Default[AuditFilterFieldModel](AuditFilterFieldAttributes),
	"troubleshoot_log_enabled": boolattr.Default(false),
}

// Model

type CoralogixModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	Endpoint               stringattr.Type                      `tfsdk:"endpoint"`
	BearerToken            stringattr.Type                      `tfsdk:"bearer_token"`
	AuditEnabled           boolattr.Type                        `tfsdk:"audit_enabled"`
	AuditFilters           listattr.Type[AuditFilterFieldModel] `tfsdk:"audit_filters"`
	TroubleshootLogEnabled boolattr.Type                        `tfsdk:"troubleshoot_log_enabled"`
}

func (m *CoralogixModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "coralogix"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *CoralogixModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

func (m *CoralogixModel) Validate(h *helpers.Handler) {
	if !m.AuditFilters.IsNull() && !m.AuditEnabled.IsNull() && !m.AuditEnabled.ValueBool() {
		h.Conflict("The audit_filters field cannot be used when audit_enabled isn't set to true")
	}
}

// Configuration

func (m *CoralogixModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.Endpoint, c, "endpoint")
	stringattr.Get(m.BearerToken, c, "bearerToken")
	boolattr.Get(m.AuditEnabled, c, "auditEnabled")
	listattr.Get(m.AuditFilters, c, "auditFilters", h)
	boolattr.Get(m.TroubleshootLogEnabled, c, "troubleshootLogEnabled")
	return c
}

func (m *CoralogixModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.Endpoint, c, "endpoint")
	stringattr.Nil(&m.BearerToken)
	boolattr.Set(&m.AuditEnabled, c, "auditEnabled")
	listattr.Set(&m.AuditFilters, c, "auditFilters", h)
	boolattr.Set(&m.TroubleshootLogEnabled, c, "troubleshootLogEnabled")
}

// Matching

func (m *CoralogixModel) GetName() stringattr.Type {
	return m.Name
}

func (m *CoralogixModel) GetID() stringattr.Type {
	return m.ID
}

func (m *CoralogixModel) SetID(id stringattr.Type) {
	m.ID = id
}
