// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/helpers"
)

var DoceboAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"base_url":      stringattr.Required(),
	"client_id":     stringattr.Required(),
	"client_secret": stringattr.SecretRequired(),
	"username":      stringattr.Required(),
	"password":      stringattr.SecretRequired(),
}

// Model

type DoceboModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	BaseURL      stringattr.Type `tfsdk:"base_url"`
	ClientID     stringattr.Type `tfsdk:"client_id"`
	ClientSecret stringattr.Type `tfsdk:"client_secret"`
	Username     stringattr.Type `tfsdk:"username"`
	Password     stringattr.Type `tfsdk:"password"`
}

func (m *DoceboModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "docebo"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *DoceboModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *DoceboModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.BaseURL, c, "baseUrl")
	stringattr.Get(m.ClientID, c, "clientId")
	stringattr.Get(m.ClientSecret, c, "clientSecret")
	stringattr.Get(m.Username, c, "username")
	stringattr.Get(m.Password, c, "password")
	return c
}

func (m *DoceboModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.BaseURL, c, "baseUrl")
	stringattr.Set(&m.ClientID, c, "clientId")
	stringattr.Nil(&m.ClientSecret)
	stringattr.Set(&m.Username, c, "username")
	stringattr.Nil(&m.Password)
}

// Matching

func (m *DoceboModel) GetName() stringattr.Type {
	return m.Name
}

func (m *DoceboModel) GetID() stringattr.Type {
	return m.ID
}

func (m *DoceboModel) SetID(id stringattr.Type) {
	m.ID = id
}
