// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/boolattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/helpers"
)

var EightByEightViberAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"sub_account_id": stringattr.Required(),
	"api_key":        stringattr.Required(),
	"country":        stringattr.Default(""),
	"use_static_ips": boolattr.Default(false),
}

// Model

type EightByEightViberModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	SubAccountID stringattr.Type `tfsdk:"sub_account_id"`
	APIKey       stringattr.Type `tfsdk:"api_key"`
	Country      stringattr.Type `tfsdk:"country"`
	UseStaticIPs boolattr.Type   `tfsdk:"use_static_ips"`
}

func (m *EightByEightViberModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "eight-by-eight-viber"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *EightByEightViberModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *EightByEightViberModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.SubAccountID, c, "subAccountId")
	stringattr.Get(m.APIKey, c, "apiKey")
	stringattr.Get(m.Country, c, "country")
	boolattr.Get(m.UseStaticIPs, c, "useStaticIps")
	return c
}

func (m *EightByEightViberModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.SubAccountID, c, "subAccountId")
	stringattr.Set(&m.APIKey, c, "apiKey")
	stringattr.Set(&m.Country, c, "country")
	boolattr.Set(&m.UseStaticIPs, c, "useStaticIps")
}

// Matching

func (m *EightByEightViberModel) GetName() stringattr.Type {
	return m.Name
}

func (m *EightByEightViberModel) GetID() stringattr.Type {
	return m.ID
}

func (m *EightByEightViberModel) SetID(id stringattr.Type) {
	m.ID = id
}
