// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/helpers"
)

var FingerprintDescopeAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"custom_domain": stringattr.Default(""),
}

// Model

type FingerprintDescopeModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	CustomDomain stringattr.Type `tfsdk:"custom_domain"`
}

func (m *FingerprintDescopeModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "fingerprint-descope"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *FingerprintDescopeModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *FingerprintDescopeModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.CustomDomain, c, "customDomain")
	return c
}

func (m *FingerprintDescopeModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.CustomDomain, c, "customDomain")
}

// Matching

func (m *FingerprintDescopeModel) GetName() stringattr.Type {
	return m.Name
}

func (m *FingerprintDescopeModel) GetID() stringattr.Type {
	return m.ID
}

func (m *FingerprintDescopeModel) SetID(id stringattr.Type) {
	m.ID = id
}
