// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/helpers"
)

var GoogleCloudTranslationAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"project_id":           stringattr.Required(),
	"service_account_json": stringattr.SecretRequired(),
}

// Model

type GoogleCloudTranslationModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	ProjectID          stringattr.Type `tfsdk:"project_id"`
	ServiceAccountJSON stringattr.Type `tfsdk:"service_account_json"`
}

func (m *GoogleCloudTranslationModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "google-cloud-translation"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *GoogleCloudTranslationModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *GoogleCloudTranslationModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.ProjectID, c, "projectId")
	stringattr.Get(m.ServiceAccountJSON, c, "serviceAccountJSON")
	return c
}

func (m *GoogleCloudTranslationModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.ProjectID, c, "projectId")
	stringattr.Nil(&m.ServiceAccountJSON)
}

// Matching

func (m *GoogleCloudTranslationModel) GetName() stringattr.Type {
	return m.Name
}

func (m *GoogleCloudTranslationModel) GetID() stringattr.Type {
	return m.ID
}

func (m *GoogleCloudTranslationModel) SetID(id stringattr.Type) {
	m.ID = id
}
