// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/helpers"
)

var GoogleMapsPlacesAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"public_api_key": stringattr.Required(),
	"address_types":  stringattr.Default(""),
	"language":       stringattr.Default(""),
	"region":         stringattr.Default(""),
}

// Model

type GoogleMapsPlacesModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	PublicAPIKey stringattr.Type `tfsdk:"public_api_key"`
	AddressTypes stringattr.Type `tfsdk:"address_types"`
	Language     stringattr.Type `tfsdk:"language"`
	Region       stringattr.Type `tfsdk:"region"`
}

func (m *GoogleMapsPlacesModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "google-maps-places"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *GoogleMapsPlacesModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *GoogleMapsPlacesModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.PublicAPIKey, c, "publicApiKey")
	stringattr.Get(m.AddressTypes, c, "addressTypes")
	stringattr.Get(m.Language, c, "language")
	stringattr.Get(m.Region, c, "region")
	return c
}

func (m *GoogleMapsPlacesModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.PublicAPIKey, c, "publicApiKey")
	stringattr.Set(&m.AddressTypes, c, "addressTypes")
	stringattr.Set(&m.Language, c, "language")
	stringattr.Set(&m.Region, c, "region")
}

// Matching

func (m *GoogleMapsPlacesModel) GetName() stringattr.Type {
	return m.Name
}

func (m *GoogleMapsPlacesModel) GetID() stringattr.Type {
	return m.ID
}

func (m *GoogleMapsPlacesModel) SetID(id stringattr.Type) {
	m.ID = id
}
