// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/boolattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/floatattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/objattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/helpers"
)

var HCaptchaValidator = objattr.NewValidator[HCaptchaModel]("must have a valid configuration")

var HCaptchaAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"site_key":            stringattr.Required(),
	"secret_key":          stringattr.SecretRequired(),
	"bot_threshold":       floatattr.Default(0.5),
	"override_assessment": boolattr.Default(false),
	"assessment_score":    floatattr.Default(0.5),
}

// Model

type HCaptchaModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	SiteKey            stringattr.Type `tfsdk:"site_key"`
	SecretKey          stringattr.Type `tfsdk:"secret_key"`
	BotThreshold       floatattr.Type  `tfsdk:"bot_threshold"`
	OverrideAssessment boolattr.Type   `tfsdk:"override_assessment"`
	AssessmentScore    floatattr.Type  `tfsdk:"assessment_score"`
}

func (m *HCaptchaModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "hcaptcha"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *HCaptchaModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

func (m *HCaptchaModel) Validate(h *helpers.Handler) {
	if !m.AssessmentScore.IsNull() && !m.OverrideAssessment.ValueBool() {
		h.Conflict("The assessment_score field cannot be used unless override_assessment is set to true")
	}
}

// Configuration

func (m *HCaptchaModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.SiteKey, c, "siteKey")
	stringattr.Get(m.SecretKey, c, "secretKey")
	floatattr.Get(m.BotThreshold, c, "botThreshold")
	boolattr.Get(m.OverrideAssessment, c, "overrideAssessment")
	floatattr.Get(m.AssessmentScore, c, "assessmentScore")
	return c
}

func (m *HCaptchaModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.SiteKey, c, "siteKey")
	stringattr.Nil(&m.SecretKey)
	floatattr.Set(&m.BotThreshold, c, "botThreshold")
	boolattr.Set(&m.OverrideAssessment, c, "overrideAssessment")
	floatattr.Set(&m.AssessmentScore, c, "assessmentScore")
}

// Matching

func (m *HCaptchaModel) GetName() stringattr.Type {
	return m.Name
}

func (m *HCaptchaModel) GetID() stringattr.Type {
	return m.ID
}

func (m *HCaptchaModel) SetID(id stringattr.Type) {
	m.ID = id
}
