// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/helpers"
)

var HIBPAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
}

// Model

type HIBPModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
}

func (m *HIBPModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "hibp"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *HIBPModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
}

// Configuration

func (m *HIBPModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	return map[string]any{}
}

// Matching

func (m *HIBPModel) GetName() stringattr.Type {
	return m.Name
}

func (m *HIBPModel) GetID() stringattr.Type {
	return m.ID
}

func (m *HIBPModel) SetID(id stringattr.Type) {
	m.ID = id
}
