// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/boolattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/objattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/helpers"
)

var LDAPValidator = objattr.NewValidator[LDAPModel]("must have a valid configuration")

var LDAPAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"server_url":          stringattr.Required(),
	"use_mtls":            boolattr.Default(false),
	"bind_dn":             stringattr.Default(""),
	"bind_password":       stringattr.SecretOptional(),
	"client_certificate":  stringattr.SecretOptional(),
	"client_key":          stringattr.SecretOptional(),
	"ca_certificate":      stringattr.SecretOptional(),
	"reject_unauthorized": boolattr.Default(true),
}

// Model

type LDAPModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	ServerURL          stringattr.Type `tfsdk:"server_url"`
	UseMTLS            boolattr.Type   `tfsdk:"use_mtls"`
	BindDN             stringattr.Type `tfsdk:"bind_dn"`
	BindPassword       stringattr.Type `tfsdk:"bind_password"`
	ClientCertificate  stringattr.Type `tfsdk:"client_certificate"`
	ClientKey          stringattr.Type `tfsdk:"client_key"`
	CACertificate      stringattr.Type `tfsdk:"ca_certificate"`
	RejectUnauthorized boolattr.Type   `tfsdk:"reject_unauthorized"`
}

func (m *LDAPModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "ldap"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *LDAPModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

func (m *LDAPModel) Validate(h *helpers.Handler) {
	if !m.BindDN.IsNull() && !m.UseMTLS.IsNull() && m.UseMTLS.ValueBool() {
		h.Conflict("The bind_dn field cannot be used when use_mtls isn't set to false")
	}
	if !m.BindDN.IsUnknown() && m.BindDN.ValueString() == "" && (m.UseMTLS.IsNull() || !m.UseMTLS.ValueBool()) {
		h.Conflict("The bind_dn field is required when use_mtls is false")
	}
	if !m.BindPassword.IsNull() && !m.UseMTLS.IsNull() && m.UseMTLS.ValueBool() {
		h.Conflict("The bind_password field cannot be used when use_mtls isn't set to false")
	}
	if !m.BindPassword.IsUnknown() && m.BindPassword.ValueString() == "" && (m.UseMTLS.IsNull() || !m.UseMTLS.ValueBool()) {
		h.Conflict("The bind_password field is required when use_mtls is false")
	}
	if !m.ClientCertificate.IsNull() && !m.UseMTLS.ValueBool() {
		h.Conflict("The client_certificate field cannot be used unless use_mtls is set to true")
	}
	if !m.ClientCertificate.IsUnknown() && m.ClientCertificate.ValueString() == "" && m.UseMTLS.ValueBool() {
		h.Conflict("The client_certificate field is required when use_mtls is set to true")
	}
	if !m.ClientKey.IsNull() && !m.UseMTLS.ValueBool() {
		h.Conflict("The client_key field cannot be used unless use_mtls is set to true")
	}
	if !m.ClientKey.IsUnknown() && m.ClientKey.ValueString() == "" && m.UseMTLS.ValueBool() {
		h.Conflict("The client_key field is required when use_mtls is set to true")
	}
	if !m.CACertificate.IsNull() && !m.UseMTLS.ValueBool() {
		h.Conflict("The ca_certificate field cannot be used unless use_mtls is set to true")
	}
}

// Configuration

func (m *LDAPModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.ServerURL, c, "serverUrl")
	boolattr.Get(m.UseMTLS, c, "useMTLS")
	stringattr.Get(m.BindDN, c, "bindDn")
	stringattr.Get(m.BindPassword, c, "bindPassword")
	stringattr.Get(m.ClientCertificate, c, "clientCert")
	stringattr.Get(m.ClientKey, c, "clientKey")
	stringattr.Get(m.CACertificate, c, "caCert")
	boolattr.Get(m.RejectUnauthorized, c, "rejectUnauthorized")
	return c
}

func (m *LDAPModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.ServerURL, c, "serverUrl")
	boolattr.Set(&m.UseMTLS, c, "useMTLS")
	stringattr.Set(&m.BindDN, c, "bindDn")
	stringattr.Nil(&m.BindPassword)
	stringattr.Nil(&m.ClientCertificate)
	stringattr.Nil(&m.ClientKey)
	stringattr.Nil(&m.CACertificate)
	boolattr.Set(&m.RejectUnauthorized, c, "rejectUnauthorized")
}

// Matching

func (m *LDAPModel) GetName() stringattr.Type {
	return m.Name
}

func (m *LDAPModel) GetID() stringattr.Type {
	return m.ID
}

func (m *LDAPModel) SetID(id stringattr.Type) {
	m.ID = id
}
