// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/helpers"
)

var LokaliseAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"api_token":            stringattr.SecretRequired(),
	"project_id":           stringattr.Required(),
	"team_id":              stringattr.Default(""),
	"card_id":              stringattr.Default(""),
	"translation_provider": stringattr.Default(""),
}

// Model

type LokaliseModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	APIToken            stringattr.Type `tfsdk:"api_token"`
	ProjectID           stringattr.Type `tfsdk:"project_id"`
	TeamID              stringattr.Type `tfsdk:"team_id"`
	CardID              stringattr.Type `tfsdk:"card_id"`
	TranslationProvider stringattr.Type `tfsdk:"translation_provider"`
}

func (m *LokaliseModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "lokalise"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *LokaliseModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *LokaliseModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.APIToken, c, "apiToken")
	stringattr.Get(m.ProjectID, c, "projectId")
	stringattr.Get(m.TeamID, c, "teamId")
	stringattr.Get(m.CardID, c, "cardId")
	stringattr.Get(m.TranslationProvider, c, "translationProvider")
	return c
}

func (m *LokaliseModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Nil(&m.APIToken)
	stringattr.Set(&m.ProjectID, c, "projectId")
	stringattr.Set(&m.TeamID, c, "teamId")
	stringattr.Set(&m.CardID, c, "cardId")
	stringattr.Set(&m.TranslationProvider, c, "translationProvider")
}

// Matching

func (m *LokaliseModel) GetName() stringattr.Type {
	return m.Name
}

func (m *LokaliseModel) GetID() stringattr.Type {
	return m.ID
}

func (m *LokaliseModel) SetID(id stringattr.Type) {
	m.ID = id
}
