// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/boolattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/listattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/objattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/helpers"
)

var MixpanelValidator = objattr.NewValidator[MixpanelModel]("must have a valid configuration")

var MixpanelAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"project_token":            stringattr.Required(),
	"api_secret":               stringattr.SecretOptional(),
	"project_id":               stringattr.Default(""),
	"service_account_username": stringattr.Default(""),
	"service_account_secret":   stringattr.SecretOptional(),
	"eu_residency":             boolattr.Default(false),
	"audit_enabled":            boolattr.Default(true),
	"audit_filters":            listattr.Default[AuditFilterFieldModel](AuditFilterFieldAttributes),
	"troubleshoot_log_enabled": boolattr.Default(false),
	"override_logs_prefix":     boolattr.Default(false),
	"logs_prefix":              stringattr.Default("descope."),
}

// Model

type MixpanelModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	ProjectToken           stringattr.Type                      `tfsdk:"project_token"`
	APISecret              stringattr.Type                      `tfsdk:"api_secret"`
	ProjectID              stringattr.Type                      `tfsdk:"project_id"`
	ServiceAccountUsername stringattr.Type                      `tfsdk:"service_account_username"`
	ServiceAccountSecret   stringattr.Type                      `tfsdk:"service_account_secret"`
	EUResidency            boolattr.Type                        `tfsdk:"eu_residency"`
	AuditEnabled           boolattr.Type                        `tfsdk:"audit_enabled"`
	AuditFilters           listattr.Type[AuditFilterFieldModel] `tfsdk:"audit_filters"`
	TroubleshootLogEnabled boolattr.Type                        `tfsdk:"troubleshoot_log_enabled"`
	OverrideLogsPrefix     boolattr.Type                        `tfsdk:"override_logs_prefix"`
	LogsPrefix             stringattr.Type                      `tfsdk:"logs_prefix"`
}

func (m *MixpanelModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "mixpanel"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *MixpanelModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

func (m *MixpanelModel) Validate(h *helpers.Handler) {
	if !m.AuditFilters.IsNull() && !m.AuditEnabled.IsNull() && !m.AuditEnabled.ValueBool() {
		h.Conflict("The audit_filters field cannot be used when audit_enabled isn't set to true")
	}
	if !m.LogsPrefix.IsNull() && !m.OverrideLogsPrefix.ValueBool() {
		h.Conflict("The logs_prefix field cannot be used unless override_logs_prefix is set to true")
	}
}

// Configuration

func (m *MixpanelModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.ProjectToken, c, "projectToken")
	stringattr.Get(m.APISecret, c, "apiSecret")
	stringattr.Get(m.ProjectID, c, "projectId")
	stringattr.Get(m.ServiceAccountUsername, c, "saUsername")
	stringattr.Get(m.ServiceAccountSecret, c, "saSecret")
	boolattr.Get(m.EUResidency, c, "euResidency")
	boolattr.Get(m.AuditEnabled, c, "auditEnabled")
	listattr.Get(m.AuditFilters, c, "auditFilters", h)
	boolattr.Get(m.TroubleshootLogEnabled, c, "troubleshootLogEnabled")
	boolattr.Get(m.OverrideLogsPrefix, c, "overrideLogsPrefix")
	stringattr.Get(m.LogsPrefix, c, "logsPrefix")
	return c
}

func (m *MixpanelModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.ProjectToken, c, "projectToken")
	stringattr.Nil(&m.APISecret)
	stringattr.Set(&m.ProjectID, c, "projectId")
	stringattr.Set(&m.ServiceAccountUsername, c, "saUsername")
	stringattr.Nil(&m.ServiceAccountSecret)
	boolattr.Set(&m.EUResidency, c, "euResidency")
	boolattr.Set(&m.AuditEnabled, c, "auditEnabled")
	listattr.Set(&m.AuditFilters, c, "auditFilters", h)
	boolattr.Set(&m.TroubleshootLogEnabled, c, "troubleshootLogEnabled")
	boolattr.Set(&m.OverrideLogsPrefix, c, "overrideLogsPrefix")
	stringattr.Set(&m.LogsPrefix, c, "logsPrefix")
}

// Matching

func (m *MixpanelModel) GetName() stringattr.Type {
	return m.Name
}

func (m *MixpanelModel) GetID() stringattr.Type {
	return m.ID
}

func (m *MixpanelModel) SetID(id stringattr.Type) {
	m.ID = id
}
