// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/boolattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/helpers"
)

var TraceableAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"secret_key": stringattr.SecretRequired(),
	"eu_region":  boolattr.Default(false),
}

// Model

type TraceableModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	SecretKey stringattr.Type `tfsdk:"secret_key"`
	EURegion  boolattr.Type   `tfsdk:"eu_region"`
}

func (m *TraceableModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "traceable"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *TraceableModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *TraceableModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.SecretKey, c, "secretKey")
	boolattr.Get(m.EURegion, c, "euRegion")
	return c
}

func (m *TraceableModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Nil(&m.SecretKey)
	boolattr.Set(&m.EURegion, c, "euRegion")
}

// Matching

func (m *TraceableModel) GetName() stringattr.Type {
	return m.Name
}

func (m *TraceableModel) GetID() stringattr.Type {
	return m.ID
}

func (m *TraceableModel) SetID(id stringattr.Type) {
	m.ID = id
}
