// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/jamescrowley321/terraform-provider-descope/internal/models/helpers"
)

var TurnstileAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"site_key":   stringattr.Required(),
	"secret_key": stringattr.SecretRequired(),
}

// Model

type TurnstileModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	SiteKey   stringattr.Type `tfsdk:"site_key"`
	SecretKey stringattr.Type `tfsdk:"secret_key"`
}

func (m *TurnstileModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "turnstile"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *TurnstileModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *TurnstileModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.SiteKey, c, "siteKey")
	stringattr.Get(m.SecretKey, c, "secretKey")
	return c
}

func (m *TurnstileModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.SiteKey, c, "siteKey")
	stringattr.Nil(&m.SecretKey)
}

// Matching

func (m *TurnstileModel) GetName() stringattr.Type {
	return m.Name
}

func (m *TurnstileModel) GetID() stringattr.Type {
	return m.ID
}

func (m *TurnstileModel) SetID(id stringattr.Type) {
	m.ID = id
}
