// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAlloyConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "alloy_connector")
	testacc.RunWithDestroyCheck(t, "descope_alloy_connector",
		// create a new alloy connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				api_token = "mybopddv"
				api_secret = "hgg666mus"
				base_url = "https://api.alloy.co/v1"
			`),
			Check: c.Check(map[string]any{
				"id":          testacc.AttributeIsSet,
				"project_id":  testacc.AttributeIsSet,
				"name":        c.Name,
				"description": "",
				"disabled":    false,
				"api_token":   "mybopddv",
				"api_secret":  "hgg666mus",
				"base_url":    "https://api.alloy.co/v1",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				api_token = "zxp6ezxf"
				api_secret = "k6o5jhwwg"
				base_url = "https://api.alloy.co/v1"
			`),
			Check: c.Check(map[string]any{
				"description": "updated",
				"disabled":    true,
				"api_token":   "zxp6ezxf",
				"api_secret":  "k6o5jhwwg",
				"base_url":    "https://api.alloy.co/v1",
			}),
		},
	)
}
