// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAmplitudeConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "amplitude_connector")
	testacc.RunWithDestroyCheck(t, "descope_amplitude_connector",
		// create a new amplitude connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				api_key = "mhvece"
				server_url = "wluvduhqc"
				server_zone = "lr32nx7xfo"
			`),
			Check: c.Check(map[string]any{
				"id":          testacc.AttributeIsSet,
				"project_id":  testacc.AttributeIsSet,
				"name":        c.Name,
				"description": "",
				"disabled":    false,
				"api_key":     "mhvece",
				"server_url":  "wluvduhqc",
				"server_zone": "lr32nx7xfo",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				api_key = "24ynkg"
				server_url = "s6qec2iy2"
				server_zone = "f245iaqq5o"
			`),
			Check: c.Check(map[string]any{
				"description": "updated",
				"disabled":    true,
				"api_key":     "24ynkg",
				"server_url":  "s6qec2iy2",
				"server_zone": "f245iaqq5o",
			}),
		},
	)
}
