// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestArkoseConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "arkose_connector")
	testacc.RunWithDestroyCheck(t, "descope_arkose_connector",
		// create a new arkose connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				public_key = "kmu3h3pg3"
				private_key = "6wzyztm5y5"
				client_base_url = "3dcpofddnrx4k"
				verify_base_url = "m5qggic77j4up"
			`),
			Check: c.Check(map[string]any{
				"id":              testacc.AttributeIsSet,
				"project_id":      testacc.AttributeIsSet,
				"name":            c.Name,
				"description":     "",
				"disabled":        false,
				"public_key":      "kmu3h3pg3",
				"private_key":     "6wzyztm5y5",
				"client_base_url": "3dcpofddnrx4k",
				"verify_base_url": "m5qggic77j4up",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				public_key = "nb3vred7d"
				private_key = "5zaotnwgqo"
				client_base_url = "whp23322bynyo"
				verify_base_url = "emj7jgw7mp74p"
			`),
			Check: c.Check(map[string]any{
				"description":     "updated",
				"disabled":        true,
				"public_key":      "nb3vred7d",
				"private_key":     "5zaotnwgqo",
				"client_base_url": "whp23322bynyo",
				"verify_base_url": "emj7jgw7mp74p",
			}),
		},
	)
}
