// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_arkose_connector is a standalone Arkose Labs connector with a server-assigned id.

var ArkoseConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Arkose Labs connector and its configuration in a Descope project. Use this connector to integrate with Arkose Labs' bot and fraud detection.",
	Attributes:          ArkoseConnectorAttributes,
}

var ArkoseConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"public_key":      stringattr.Required(),
	"private_key":     stringattr.SecretRequired(),
	"client_base_url": stringattr.Default(""),
	"verify_base_url": stringattr.Default(""),
}

// Model

type ArkoseConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	PublicKey     stringattr.Type `tfsdk:"public_key"`
	PrivateKey    stringattr.Type `tfsdk:"private_key"`
	ClientBaseURL stringattr.Type `tfsdk:"client_base_url"`
	VerifyBaseURL stringattr.Type `tfsdk:"verify_base_url"`
}

func (m *ArkoseConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "arkose"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *ArkoseConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *ArkoseConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.PublicKey, c, "publicKey")
	stringattr.Get(m.PrivateKey, c, "privateKey")
	stringattr.Get(m.ClientBaseURL, c, "clientBaseUrl")
	stringattr.Get(m.VerifyBaseURL, c, "verifyBaseUrl")
	return c
}

func (m *ArkoseConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.PublicKey, c, "publicKey")
	stringattr.SetSecret(&m.PrivateKey, c, "privateKey", h)
	stringattr.Set(&m.ClientBaseURL, c, "clientBaseUrl")
	stringattr.Set(&m.VerifyBaseURL, c, "verifyBaseUrl")
}

func (m *ArkoseConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *ArkoseConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *ArkoseConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
