// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/listattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/objattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/strmapattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_audit_webhook_connector is a standalone Audit Webhook connector with a server-assigned id.

var AuditWebhookConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Audit Webhook connector and its configuration in a Descope project. Send audit events to a custom webhook.",
	Attributes:          AuditWebhookConnectorAttributes,
}

var AuditWebhookConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"base_url":       stringattr.Required(),
	"authentication": objattr.Default(HTTPAuthFieldDefault, HTTPAuthFieldAttributes, HTTPAuthFieldValidator),
	"headers":        strmapattr.Default(),
	"secret_headers": strmapattr.Secret(),
	"hmac_secret":    stringattr.SecretOptional(),
	"insecure":       boolattr.Default(false),
	"audit_filters":  listattr.Default[AuditFilterFieldModel](AuditFilterFieldAttributes),
}

// Model

type AuditWebhookConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	BaseURL        stringattr.Type                      `tfsdk:"base_url"`
	Authentication objattr.Type[HTTPAuthFieldModel]     `tfsdk:"authentication"`
	Headers        strmapattr.Type                      `tfsdk:"headers"`
	SecretHeaders  strmapattr.Type                      `tfsdk:"secret_headers"`
	HMACSecret     stringattr.Type                      `tfsdk:"hmac_secret"`
	Insecure       boolattr.Type                        `tfsdk:"insecure"`
	AuditFilters   listattr.Type[AuditFilterFieldModel] `tfsdk:"audit_filters"`
}

func (m *AuditWebhookConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "audit-webhook"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *AuditWebhookConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *AuditWebhookConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.BaseURL, c, "baseUrl")
	objattr.Get(m.Authentication, c, "authentication", h)
	getSecretObject(m.Headers, m.SecretHeaders, c, "headers", h)
	stringattr.Get(m.HMACSecret, c, "hmacSecret")
	boolattr.Get(m.Insecure, c, "insecure")
	listattr.Get(m.AuditFilters, c, "auditFilters", h)
	return c
}

func (m *AuditWebhookConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.BaseURL, c, "baseUrl")
	objattr.Set(&m.Authentication, c, "authentication", h)
	setSecretObject(&m.Headers, &m.SecretHeaders, c, "headers", h)
	stringattr.SetSecret(&m.HMACSecret, c, "hmacSecret", h)
	boolattr.Set(&m.Insecure, c, "insecure")
	listattr.Set(&m.AuditFilters, c, "auditFilters", h)
}

func (m *AuditWebhookConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *AuditWebhookConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *AuditWebhookConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
