// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/listattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_aws_eventbridge_connector is a standalone AWS EventBridge connector with a server-assigned id.

var AWSEventBridgeConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a AWS EventBridge connector and its configuration in a Descope project. Stream authentication audit logs with the Amazon EventBridge connector.",
	Attributes:          AWSEventBridgeConnectorAttributes,
}

var AWSEventBridgeConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"auth_type":                stringattr.Default("credentials", stringvalidator.OneOf("credentials", "assumeRole")),
	"access_key_id":            stringattr.SecretOptional(),
	"secret_access_key":        stringattr.SecretOptional(),
	"role_arn":                 stringattr.Default(""),
	"external_id":              stringattr.Default(""),
	"region":                   stringattr.Required(),
	"event_bus_name":           stringattr.Required(),
	"detail_type":              stringattr.Required(),
	"source":                   stringattr.Required(),
	"audit_enabled":            boolattr.Default(true),
	"audit_filters":            listattr.Default[AuditFilterFieldModel](AuditFilterFieldAttributes),
	"troubleshoot_log_enabled": boolattr.Default(false),
	"mask_pii":                 boolattr.Default(false),
}

// Model

type AWSEventBridgeConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	AuthType               stringattr.Type                      `tfsdk:"auth_type"`
	AccessKeyID            stringattr.Type                      `tfsdk:"access_key_id"`
	SecretAccessKey        stringattr.Type                      `tfsdk:"secret_access_key"`
	RoleARN                stringattr.Type                      `tfsdk:"role_arn"`
	ExternalID             stringattr.Type                      `tfsdk:"external_id"`
	Region                 stringattr.Type                      `tfsdk:"region"`
	EventBusName           stringattr.Type                      `tfsdk:"event_bus_name"`
	DetailType             stringattr.Type                      `tfsdk:"detail_type"`
	Source                 stringattr.Type                      `tfsdk:"source"`
	AuditEnabled           boolattr.Type                        `tfsdk:"audit_enabled"`
	AuditFilters           listattr.Type[AuditFilterFieldModel] `tfsdk:"audit_filters"`
	TroubleshootLogEnabled boolattr.Type                        `tfsdk:"troubleshoot_log_enabled"`
	MaskPII                boolattr.Type                        `tfsdk:"mask_pii"`
}

func (m *AWSEventBridgeConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "aws-eventbridge"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	m.Validate(h)
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *AWSEventBridgeConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

func (m *AWSEventBridgeConnectorModel) Validate(h *helpers.Handler) {
	if m.AccessKeyID.ValueString() != "" && m.AuthType.ValueString() != "" && m.AuthType.ValueString() != "credentials" {
		h.Conflict("The access_key_id field can only be used when auth_type is set to 'credentials'")
	}
	if m.AccessKeyID.ValueString() == "" && !m.AccessKeyID.IsUnknown() && m.AuthType.ValueString() == "credentials" {
		h.Conflict("The access_key_id field is required when auth_type is set to 'credentials'")
	}
	if m.SecretAccessKey.ValueString() != "" && m.AuthType.ValueString() != "" && m.AuthType.ValueString() != "credentials" {
		h.Conflict("The secret_access_key field can only be used when auth_type is set to 'credentials'")
	}
	if m.SecretAccessKey.ValueString() == "" && !m.SecretAccessKey.IsUnknown() && m.AuthType.ValueString() == "credentials" {
		h.Conflict("The secret_access_key field is required when auth_type is set to 'credentials'")
	}
	if m.RoleARN.ValueString() != "" && m.AuthType.ValueString() != "" && m.AuthType.ValueString() != "assumeRole" {
		h.Conflict("The role_arn field can only be used when auth_type is set to 'assumeRole'")
	}
	if m.RoleARN.ValueString() == "" && !m.RoleARN.IsUnknown() && m.AuthType.ValueString() == "assumeRole" {
		h.Conflict("The role_arn field is required when auth_type is set to 'assumeRole'")
	}
	if m.ExternalID.ValueString() != "" && m.AuthType.ValueString() != "" && m.AuthType.ValueString() != "assumeRole" {
		h.Conflict("The external_id field can only be used when auth_type is set to 'assumeRole'")
	}
	if m.ExternalID.ValueString() == "" && !m.ExternalID.IsUnknown() && m.AuthType.ValueString() == "assumeRole" {
		h.Conflict("The external_id field is required when auth_type is set to 'assumeRole'")
	}
	if !m.AuditFilters.IsEmpty() && !m.AuditEnabled.IsUnknown() && !m.AuditEnabled.IsNull() && !m.AuditEnabled.ValueBool() {
		h.Conflict("The audit_filters field cannot be used when audit_enabled isn't set to true")
	}
}

// Configuration

func (m *AWSEventBridgeConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.AuthType, c, "authType")
	stringattr.Get(m.AccessKeyID, c, "accessKeyId")
	stringattr.Get(m.SecretAccessKey, c, "secretAccessKey")
	stringattr.Get(m.RoleARN, c, "roleArn")
	stringattr.Get(m.ExternalID, c, "externalId")
	stringattr.Get(m.Region, c, "region")
	stringattr.Get(m.EventBusName, c, "eventBusName")
	stringattr.Get(m.DetailType, c, "detailType")
	stringattr.Get(m.Source, c, "source")
	boolattr.Get(m.AuditEnabled, c, "auditEnabled")
	listattr.Get(m.AuditFilters, c, "auditFilters", h)
	boolattr.Get(m.TroubleshootLogEnabled, c, "troubleshootLogEnabled")
	boolattr.Get(m.MaskPII, c, "maskPII")
	return c
}

func (m *AWSEventBridgeConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.AuthType, c, "authType")
	stringattr.SetSecret(&m.AccessKeyID, c, "accessKeyId", h)
	stringattr.SetSecret(&m.SecretAccessKey, c, "secretAccessKey", h)
	stringattr.Set(&m.RoleARN, c, "roleArn")
	stringattr.Set(&m.ExternalID, c, "externalId")
	stringattr.Set(&m.Region, c, "region")
	stringattr.Set(&m.EventBusName, c, "eventBusName")
	stringattr.Set(&m.DetailType, c, "detailType")
	stringattr.Set(&m.Source, c, "source")
	boolattr.Set(&m.AuditEnabled, c, "auditEnabled")
	listattr.Set(&m.AuditFilters, c, "auditFilters", h)
	boolattr.Set(&m.TroubleshootLogEnabled, c, "troubleshootLogEnabled")
	boolattr.Set(&m.MaskPII, c, "maskPII")
}

func (m *AWSEventBridgeConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *AWSEventBridgeConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *AWSEventBridgeConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
