// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestBitsightConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "bitsight_connector")
	testacc.RunWithDestroyCheck(t, "descope_bitsight_connector",
		// create a new bitsight connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				client_id = "sgetgyvq"
				client_secret = "tjpxl7uy4wbb"
			`),
			Check: c.Check(map[string]any{
				"id":            testacc.AttributeIsSet,
				"project_id":    testacc.AttributeIsSet,
				"name":          c.Name,
				"description":   "",
				"disabled":      false,
				"client_id":     "sgetgyvq",
				"client_secret": "tjpxl7uy4wbb",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				client_id = "44l33qeq"
				client_secret = "hgw76gicp7vp"
			`),
			Check: c.Check(map[string]any{
				"description":   "updated",
				"disabled":      true,
				"client_id":     "44l33qeq",
				"client_secret": "hgw76gicp7vp",
			}),
		},
	)
}
