// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestDatadogConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "datadog_connector")
	testacc.RunWithDestroyCheck(t, "descope_datadog_connector",
		// create a new datadog connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				api_key = "mhvece"
				site = "7oxa"
				source = "ihhwpf"
				tags = "s6gc"
				audit_enabled = true
				audit_filters = [{ key = "actions", operator = "includes", values = ["kekpon4oj34w"] }]
				troubleshoot_log_enabled = false
				mask_pii = false
			`),
			Check: c.Check(map[string]any{
				"id":                       testacc.AttributeIsSet,
				"project_id":               testacc.AttributeIsSet,
				"name":                     c.Name,
				"description":              "",
				"disabled":                 false,
				"api_key":                  "mhvece",
				"site":                     "7oxa",
				"source":                   "ihhwpf",
				"tags":                     "s6gc",
				"audit_enabled":            true,
				"audit_filters.0.values":   []string{"kekpon4oj34w"},
				"troubleshoot_log_enabled": false,
				"mask_pii":                 false,
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				api_key = "24ynkg"
				site = "gbul"
				source = "s6ekuk"
				tags = "fnld"
				audit_enabled = true
				audit_filters = [{ key = "actions", operator = "includes", values = ["po4by43vyqpb"] }]
				troubleshoot_log_enabled = true
				mask_pii = true
			`),
			Check: c.Check(map[string]any{
				"description":              "updated",
				"disabled":                 true,
				"api_key":                  "24ynkg",
				"site":                     "gbul",
				"source":                   "s6ekuk",
				"tags":                     "fnld",
				"audit_enabled":            true,
				"audit_filters.0.values":   []string{"po4by43vyqpb"},
				"troubleshoot_log_enabled": true,
				"mask_pii":                 true,
			}),
		},
	)
}
