// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_eight_by_eight_viber_connector is a standalone 8x8 for Viber connector with a server-assigned id.

var EightByEightViberConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a 8x8 for Viber connector and its configuration in a Descope project. Use the connector to send Viber messages to the user.",
	Attributes:          EightByEightViberConnectorAttributes,
}

var EightByEightViberConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"sub_account_id": stringattr.Required(),
	"api_key":        stringattr.Required(),
	"country":        stringattr.Default(""),
	"use_static_ips": boolattr.Default(false),
}

// Model

type EightByEightViberConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	SubAccountID stringattr.Type `tfsdk:"sub_account_id"`
	APIKey       stringattr.Type `tfsdk:"api_key"`
	Country      stringattr.Type `tfsdk:"country"`
	UseStaticIPs boolattr.Type   `tfsdk:"use_static_ips"`
}

func (m *EightByEightViberConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "eight-by-eight-viber"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *EightByEightViberConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *EightByEightViberConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.SubAccountID, c, "subAccountId")
	stringattr.Get(m.APIKey, c, "apiKey")
	stringattr.Get(m.Country, c, "country")
	boolattr.Get(m.UseStaticIPs, c, "useStaticIps")
	return c
}

func (m *EightByEightViberConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.SubAccountID, c, "subAccountId")
	stringattr.Set(&m.APIKey, c, "apiKey")
	stringattr.Set(&m.Country, c, "country")
	boolattr.Set(&m.UseStaticIPs, c, "useStaticIps")
}

func (m *EightByEightViberConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *EightByEightViberConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *EightByEightViberConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
