// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestExternalTokenHTTPConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "external_token_http_connector")
	testacc.RunWithDestroyCheck(t, "descope_external_token_http_connector",
		// create a new external-token-http connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				endpoint = "w27xxsgz"
				authentication = {
    							bearer_token = "xhmqmkcfhe4mk6"
    						}
				headers = { "X-Plain" = "g6htpmp" }
				secret_headers = { "X-Secret" = "j57dfuysuuapr" }
				hmac_secret = "ooxzct5yxz"
				insecure = false
				use_static_ips = false
			`),
			Check: c.Check(map[string]any{
				"id":                          testacc.AttributeIsSet,
				"project_id":                  testacc.AttributeIsSet,
				"name":                        c.Name,
				"description":                 "",
				"disabled":                    false,
				"endpoint":                    "w27xxsgz",
				"authentication.bearer_token": "xhmqmkcfhe4mk6",
				"headers.X-Plain":             "g6htpmp",
				"secret_headers.X-Secret":     "j57dfuysuuapr",
				"hmac_secret":                 "ooxzct5yxz",
				"insecure":                    false,
				"use_static_ips":              false,
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				endpoint = "ef4vxrwc"
				authentication = {
    							bearer_token = "r6zxhdnnw7dqoq"
    						}
				headers = { "X-Plain" = "7xiojfk" }
				secret_headers = { "X-Secret" = "yh4n7htn6b32r" }
				hmac_secret = "twukowwuij"
				insecure = true
				use_static_ips = true
			`),
			Check: c.Check(map[string]any{
				"description":                 "updated",
				"disabled":                    true,
				"endpoint":                    "ef4vxrwc",
				"authentication.bearer_token": "r6zxhdnnw7dqoq",
				"headers.X-Plain":             "7xiojfk",
				"secret_headers.X-Secret":     "yh4n7htn6b32r",
				"hmac_secret":                 "twukowwuij",
				"insecure":                    true,
				"use_static_ips":              true,
			}),
		},
	)
}
