// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_fingerprint_descope_connector is a standalone Descope Fingerprint connector with a server-assigned id.

var FingerprintDescopeConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Descope Fingerprint connector and its configuration in a Descope project. Descope Fingerprint capabilities for fraud detection and risk assessment.",
	Attributes:          FingerprintDescopeConnectorAttributes,
}

var FingerprintDescopeConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"custom_domain": stringattr.Default(""),
}

// Model

type FingerprintDescopeConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	CustomDomain stringattr.Type `tfsdk:"custom_domain"`
}

func (m *FingerprintDescopeConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "fingerprint-descope"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *FingerprintDescopeConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *FingerprintDescopeConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.CustomDomain, c, "customDomain")
	return c
}

func (m *FingerprintDescopeConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.CustomDomain, c, "customDomain")
}

func (m *FingerprintDescopeConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *FingerprintDescopeConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *FingerprintDescopeConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
