// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestFirebaseAdminConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "firebase_admin_connector")
	testacc.RunWithDestroyCheck(t, "descope_firebase_admin_connector",
		// create a new firebase-admin connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				service_account = "w4nbeixmfpmumt"
			`),
			Check: c.Check(map[string]any{
				"id":              testacc.AttributeIsSet,
				"project_id":      testacc.AttributeIsSet,
				"name":            c.Name,
				"description":     "",
				"disabled":        false,
				"service_account": "w4nbeixmfpmumt",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				service_account = "zprqfkeckzogth"
			`),
			Check: c.Check(map[string]any{
				"description":     "updated",
				"disabled":        true,
				"service_account": "zprqfkeckzogth",
			}),
		},
	)
}
