// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_forter_connector is a standalone Forter connector with a server-assigned id.

var ForterConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Forter connector and its configuration in a Descope project. Leverage ML-based risk scores for fraud prevention with the Forter connector.",
	Attributes:          ForterConnectorAttributes,
}

var ForterConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"site_id":             stringattr.Required(),
	"secret_key":          stringattr.SecretRequired(),
	"api_version":         stringattr.Default(""),
	"overrides":           boolattr.Default(false),
	"override_ip_address": stringattr.Default(""),
	"override_user_email": stringattr.Default(""),
}

// Model

type ForterConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	SiteID            stringattr.Type `tfsdk:"site_id"`
	SecretKey         stringattr.Type `tfsdk:"secret_key"`
	APIVersion        stringattr.Type `tfsdk:"api_version"`
	Overrides         boolattr.Type   `tfsdk:"overrides"`
	OverrideIPAddress stringattr.Type `tfsdk:"override_ip_address"`
	OverrideUserEmail stringattr.Type `tfsdk:"override_user_email"`
}

func (m *ForterConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "forter"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	m.Validate(h)
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *ForterConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

func (m *ForterConnectorModel) Validate(h *helpers.Handler) {
	if m.OverrideIPAddress.ValueString() != "" && !m.Overrides.IsUnknown() && !m.Overrides.ValueBool() {
		h.Conflict("The override_ip_address field cannot be used unless overrides is set to true")
	}
	if m.OverrideUserEmail.ValueString() != "" && !m.Overrides.IsUnknown() && !m.Overrides.ValueBool() {
		h.Conflict("The override_user_email field cannot be used unless overrides is set to true")
	}
}

// Configuration

func (m *ForterConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.SiteID, c, "siteId")
	stringattr.Get(m.SecretKey, c, "secretKey")
	stringattr.Get(m.APIVersion, c, "apiVersion")
	boolattr.Get(m.Overrides, c, "overrides")
	stringattr.Get(m.OverrideIPAddress, c, "overrideIpAddress")
	stringattr.Get(m.OverrideUserEmail, c, "overrideUserEmail")
	return c
}

func (m *ForterConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.SiteID, c, "siteId")
	stringattr.SetSecret(&m.SecretKey, c, "secretKey", h)
	stringattr.Set(&m.APIVersion, c, "apiVersion")
	boolattr.Set(&m.Overrides, c, "overrides")
	stringattr.Set(&m.OverrideIPAddress, c, "overrideIpAddress")
	stringattr.Set(&m.OverrideUserEmail, c, "overrideUserEmail")
}

func (m *ForterConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *ForterConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *ForterConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
