// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestGoogleCloudTranslationConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "google_cloud_translation_connector")
	testacc.RunWithDestroyCheck(t, "descope_google_cloud_translation_connector",
		// create a new google-cloud-translation connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				config_project_id = "yhw7b6yel"
				service_account_json = "4wrifr235ikphcluwt"
			`),
			Check: c.Check(map[string]any{
				"id":                   testacc.AttributeIsSet,
				"project_id":           testacc.AttributeIsSet,
				"name":                 c.Name,
				"description":          "",
				"disabled":             false,
				"config_project_id":    "yhw7b6yel",
				"service_account_json": "4wrifr235ikphcluwt",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				config_project_id = "kyt3656wh"
				service_account_json = "tmchsduxd4n42uo2pb"
			`),
			Check: c.Check(map[string]any{
				"description":          "updated",
				"disabled":             true,
				"config_project_id":    "kyt3656wh",
				"service_account_json": "tmchsduxd4n42uo2pb",
			}),
		},
	)
}
