// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestGoogleMapsPlacesConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "google_maps_places_connector")
	testacc.RunWithDestroyCheck(t, "descope_google_maps_places_connector",
		// create a new google-maps-places connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				public_api_key = "htt624yz4z6i"
				address_types = "ww5orzyeof5s"
				language = "utxtas5e"
				region = "y2l5fg"
			`),
			Check: c.Check(map[string]any{
				"id":             testacc.AttributeIsSet,
				"project_id":     testacc.AttributeIsSet,
				"name":           c.Name,
				"description":    "",
				"disabled":       false,
				"public_api_key": "htt624yz4z6i",
				"address_types":  "ww5orzyeof5s",
				"language":       "utxtas5e",
				"region":         "y2l5fg",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				public_api_key = "sa3gjeq6eyuu"
				address_types = "epza73guz3l7"
				language = "hqekgski"
				region = "versrj"
			`),
			Check: c.Check(map[string]any{
				"description":    "updated",
				"disabled":       true,
				"public_api_key": "sa3gjeq6eyuu",
				"address_types":  "epza73guz3l7",
				"language":       "hqekgski",
				"region":         "versrj",
			}),
		},
	)
}
