// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestGroundcoverConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "groundcover_connector")
	testacc.RunWithDestroyCheck(t, "descope_groundcover_connector",
		// create a new groundcover connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				endpoint = "w27xxsgz"
				ingestion_key = "ovls2taivyns"
				environment_name = "atjbgae4zikeyoj"
				service_name = "a2oorm5qgsr"
				audit_enabled = true
				audit_filters = [{ key = "actions", operator = "includes", values = ["kekpon4oj34w"] }]
				troubleshoot_log_enabled = false
				mask_pii = false
			`),
			Check: c.Check(map[string]any{
				"id":                       testacc.AttributeIsSet,
				"project_id":               testacc.AttributeIsSet,
				"name":                     c.Name,
				"description":              "",
				"disabled":                 false,
				"endpoint":                 "w27xxsgz",
				"ingestion_key":            "ovls2taivyns",
				"environment_name":         "atjbgae4zikeyoj",
				"service_name":             "a2oorm5qgsr",
				"audit_enabled":            true,
				"audit_filters.0.values":   []string{"kekpon4oj34w"},
				"troubleshoot_log_enabled": false,
				"mask_pii":                 false,
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				endpoint = "ef4vxrwc"
				ingestion_key = "a23quob5myi2"
				environment_name = "iiaa7u4xu7dtdyd"
				service_name = "lvsuu77flnh"
				audit_enabled = true
				audit_filters = [{ key = "actions", operator = "includes", values = ["po4by43vyqpb"] }]
				troubleshoot_log_enabled = true
				mask_pii = true
			`),
			Check: c.Check(map[string]any{
				"description":              "updated",
				"disabled":                 true,
				"endpoint":                 "ef4vxrwc",
				"ingestion_key":            "a23quob5myi2",
				"environment_name":         "iiaa7u4xu7dtdyd",
				"service_name":             "lvsuu77flnh",
				"audit_enabled":            true,
				"audit_filters.0.values":   []string{"po4by43vyqpb"},
				"troubleshoot_log_enabled": true,
				"mask_pii":                 true,
			}),
		},
	)
}
