// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_hibp_connector is a standalone Have I Been Pwned connector with a server-assigned id.

var HIBPConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Have I Been Pwned connector and its configuration in a Descope project. Check if passwords have been previously exposed in data breaches with the Have I Been Pwned connector.",
	Attributes:          HIBPConnectorAttributes,
}

var HIBPConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),
}

// Model

type HIBPConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`
}

func (m *HIBPConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "hibp"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *HIBPConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
}

// Configuration

func (m *HIBPConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	return map[string]any{}
}

func (m *HIBPConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *HIBPConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *HIBPConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
