// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"slices"

	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/floatattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/objattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/strmapattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_http_connector is a standalone Generic HTTP connector with a server-assigned id.

var HTTPConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Generic HTTP connector and its configuration in a Descope project. A general purpose HTTP client.",
	Attributes:          HTTPConnectorAttributes,
}

var HTTPConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"base_url":                   stringattr.Required(),
	"authentication":             objattr.Default(HTTPAuthFieldDefault, HTTPAuthFieldAttributes, HTTPAuthFieldValidator),
	"headers":                    strmapattr.Default(),
	"secret_headers":             strmapattr.Secret(),
	"hmac_secret":                stringattr.SecretOptional(),
	"aws_auth_type":              stringattr.Default("none", stringvalidator.OneOf("", "none", "credentials", "assumeRole")),
	"aws_access_key_id":          stringattr.SecretOptional(),
	"aws_secret_access_key":      stringattr.SecretOptional(),
	"aws_role_arn":               stringattr.Default(""),
	"aws_external_id":            stringattr.Default(""),
	"aws_region":                 stringattr.Default(""),
	"aws_service":                stringattr.Default(""),
	"use_mtls":                   boolattr.Default(false),
	"client_certificate":         stringattr.SecretOptional(),
	"client_key":                 stringattr.SecretOptional(),
	"ca_certificate":             stringattr.SecretOptional(),
	"rfc9421_signing_enabled":    boolattr.Default(false),
	"rfc9421_private_key":        stringattr.SecretOptional(),
	"rfc9421_key_id":             stringattr.Default(""),
	"rfc9421_components":         stringattr.Default(""),
	"rfc9421_signature_ttl":      floatattr.Default(300),
	"insecure":                   boolattr.Default(false),
	"include_headers_in_context": boolattr.Default(false),
	"use_static_ips":             boolattr.Default(false),
}

// Model

type HTTPConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	BaseURL                 stringattr.Type                  `tfsdk:"base_url"`
	Authentication          objattr.Type[HTTPAuthFieldModel] `tfsdk:"authentication"`
	Headers                 strmapattr.Type                  `tfsdk:"headers"`
	SecretHeaders           strmapattr.Type                  `tfsdk:"secret_headers"`
	HMACSecret              stringattr.Type                  `tfsdk:"hmac_secret"`
	AWSAuthType             stringattr.Type                  `tfsdk:"aws_auth_type"`
	AWSAccessKeyID          stringattr.Type                  `tfsdk:"aws_access_key_id"`
	AWSSecretAccessKey      stringattr.Type                  `tfsdk:"aws_secret_access_key"`
	AWSRoleARN              stringattr.Type                  `tfsdk:"aws_role_arn"`
	AWSExternalID           stringattr.Type                  `tfsdk:"aws_external_id"`
	AWSRegion               stringattr.Type                  `tfsdk:"aws_region"`
	AWSService              stringattr.Type                  `tfsdk:"aws_service"`
	UseMTLS                 boolattr.Type                    `tfsdk:"use_mtls"`
	ClientCertificate       stringattr.Type                  `tfsdk:"client_certificate"`
	ClientKey               stringattr.Type                  `tfsdk:"client_key"`
	CACertificate           stringattr.Type                  `tfsdk:"ca_certificate"`
	RFC9421SigningEnabled   boolattr.Type                    `tfsdk:"rfc9421_signing_enabled"`
	RFC9421PrivateKey       stringattr.Type                  `tfsdk:"rfc9421_private_key"`
	RFC9421KeyID            stringattr.Type                  `tfsdk:"rfc9421_key_id"`
	RFC9421Components       stringattr.Type                  `tfsdk:"rfc9421_components"`
	RFC9421SignatureTTL     floatattr.Type                   `tfsdk:"rfc9421_signature_ttl"`
	Insecure                boolattr.Type                    `tfsdk:"insecure"`
	IncludeHeadersInContext boolattr.Type                    `tfsdk:"include_headers_in_context"`
	UseStaticIPs            boolattr.Type                    `tfsdk:"use_static_ips"`
}

func (m *HTTPConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "http"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	m.Validate(h)
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *HTTPConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

func (m *HTTPConnectorModel) Validate(h *helpers.Handler) {
	if m.AWSAccessKeyID.ValueString() != "" && m.AWSAuthType.ValueString() != "" && m.AWSAuthType.ValueString() != "credentials" {
		h.Conflict("The aws_access_key_id field can only be used when aws_auth_type is set to 'credentials'")
	}
	if m.AWSAccessKeyID.ValueString() == "" && !m.AWSAccessKeyID.IsUnknown() && m.AWSAuthType.ValueString() == "credentials" {
		h.Conflict("The aws_access_key_id field is required when aws_auth_type is set to 'credentials'")
	}
	if m.AWSSecretAccessKey.ValueString() != "" && m.AWSAuthType.ValueString() != "" && m.AWSAuthType.ValueString() != "credentials" {
		h.Conflict("The aws_secret_access_key field can only be used when aws_auth_type is set to 'credentials'")
	}
	if m.AWSSecretAccessKey.ValueString() == "" && !m.AWSSecretAccessKey.IsUnknown() && m.AWSAuthType.ValueString() == "credentials" {
		h.Conflict("The aws_secret_access_key field is required when aws_auth_type is set to 'credentials'")
	}
	if m.AWSRoleARN.ValueString() != "" && m.AWSAuthType.ValueString() != "" && m.AWSAuthType.ValueString() != "assumeRole" {
		h.Conflict("The aws_role_arn field can only be used when aws_auth_type is set to 'assumeRole'")
	}
	if m.AWSRoleARN.ValueString() == "" && !m.AWSRoleARN.IsUnknown() && m.AWSAuthType.ValueString() == "assumeRole" {
		h.Conflict("The aws_role_arn field is required when aws_auth_type is set to 'assumeRole'")
	}
	if m.AWSExternalID.ValueString() != "" && m.AWSAuthType.ValueString() != "" && m.AWSAuthType.ValueString() != "assumeRole" {
		h.Conflict("The aws_external_id field can only be used when aws_auth_type is set to 'assumeRole'")
	}
	if m.AWSExternalID.ValueString() == "" && !m.AWSExternalID.IsUnknown() && m.AWSAuthType.ValueString() == "assumeRole" {
		h.Conflict("The aws_external_id field is required when aws_auth_type is set to 'assumeRole'")
	}
	if m.AWSRegion.ValueString() != "" && m.AWSAuthType.ValueString() != "" && !slices.Contains([]string{"credentials", "assumeRole"}, m.AWSAuthType.ValueString()) {
		h.Conflict("The aws_region field can only be used when aws_auth_type is one of [credentials assumeRole]")
	}
	if m.AWSRegion.ValueString() == "" && !m.AWSRegion.IsUnknown() && slices.Contains([]string{"credentials", "assumeRole"}, m.AWSAuthType.ValueString()) {
		h.Conflict("The aws_region field is required when aws_auth_type is one of [credentials assumeRole]")
	}
	if m.AWSService.ValueString() != "" && m.AWSAuthType.ValueString() != "" && !slices.Contains([]string{"credentials", "assumeRole"}, m.AWSAuthType.ValueString()) {
		h.Conflict("The aws_service field can only be used when aws_auth_type is one of [credentials assumeRole]")
	}
	if m.AWSService.ValueString() == "" && !m.AWSService.IsUnknown() && slices.Contains([]string{"credentials", "assumeRole"}, m.AWSAuthType.ValueString()) {
		h.Conflict("The aws_service field is required when aws_auth_type is one of [credentials assumeRole]")
	}
	if m.ClientCertificate.ValueString() != "" && !m.UseMTLS.IsUnknown() && !m.UseMTLS.ValueBool() {
		h.Conflict("The client_certificate field cannot be used unless use_mtls is set to true")
	}
	if !m.ClientCertificate.IsUnknown() && m.ClientCertificate.ValueString() == "" && m.UseMTLS.ValueBool() {
		h.Conflict("The client_certificate field is required when use_mtls is set to true")
	}
	if m.ClientKey.ValueString() != "" && !m.UseMTLS.IsUnknown() && !m.UseMTLS.ValueBool() {
		h.Conflict("The client_key field cannot be used unless use_mtls is set to true")
	}
	if !m.ClientKey.IsUnknown() && m.ClientKey.ValueString() == "" && m.UseMTLS.ValueBool() {
		h.Conflict("The client_key field is required when use_mtls is set to true")
	}
	if m.CACertificate.ValueString() != "" && !m.UseMTLS.IsUnknown() && !m.UseMTLS.ValueBool() {
		h.Conflict("The ca_certificate field cannot be used unless use_mtls is set to true")
	}
	if m.RFC9421PrivateKey.ValueString() != "" && !m.RFC9421SigningEnabled.IsUnknown() && !m.RFC9421SigningEnabled.ValueBool() {
		h.Conflict("The rfc9421_private_key field cannot be used unless rfc9421_signing_enabled is set to true")
	}
	if m.RFC9421KeyID.ValueString() != "" && !m.RFC9421SigningEnabled.IsUnknown() && !m.RFC9421SigningEnabled.ValueBool() {
		h.Conflict("The rfc9421_key_id field cannot be used unless rfc9421_signing_enabled is set to true")
	}
	if m.RFC9421Components.ValueString() != "" && !m.RFC9421SigningEnabled.IsUnknown() && !m.RFC9421SigningEnabled.ValueBool() {
		h.Conflict("The rfc9421_components field cannot be used unless rfc9421_signing_enabled is set to true")
	}
}

// Configuration

func (m *HTTPConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.BaseURL, c, "baseUrl")
	objattr.Get(m.Authentication, c, "authentication", h)
	getSecretObject(m.Headers, m.SecretHeaders, c, "headers", h)
	stringattr.Get(m.HMACSecret, c, "hmacSecret")
	stringattr.Get(m.AWSAuthType, c, "awsAuthType")
	stringattr.Get(m.AWSAccessKeyID, c, "awsAccessKeyId")
	stringattr.Get(m.AWSSecretAccessKey, c, "awsSecretAccessKey")
	stringattr.Get(m.AWSRoleARN, c, "awsRoleArn")
	stringattr.Get(m.AWSExternalID, c, "awsExternalId")
	stringattr.Get(m.AWSRegion, c, "awsRegion")
	stringattr.Get(m.AWSService, c, "awsService")
	boolattr.Get(m.UseMTLS, c, "useMTLS")
	stringattr.Get(m.ClientCertificate, c, "clientCert")
	stringattr.Get(m.ClientKey, c, "clientKey")
	stringattr.Get(m.CACertificate, c, "caCert")
	boolattr.Get(m.RFC9421SigningEnabled, c, "rfc9421SigningEnabled")
	stringattr.Get(m.RFC9421PrivateKey, c, "rfc9421PrivateKey")
	stringattr.Get(m.RFC9421KeyID, c, "rfc9421KeyId")
	stringattr.Get(m.RFC9421Components, c, "rfc9421Components")
	floatattr.Get(m.RFC9421SignatureTTL, c, "rfc9421SignatureTTL")
	boolattr.Get(m.Insecure, c, "insecure")
	boolattr.Get(m.IncludeHeadersInContext, c, "includeHeadersInContext")
	boolattr.Get(m.UseStaticIPs, c, "useStaticIps")
	return c
}

func (m *HTTPConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.BaseURL, c, "baseUrl")
	objattr.Set(&m.Authentication, c, "authentication", h)
	setSecretObject(&m.Headers, &m.SecretHeaders, c, "headers", h)
	stringattr.SetSecret(&m.HMACSecret, c, "hmacSecret", h)
	stringattr.Set(&m.AWSAuthType, c, "awsAuthType")
	stringattr.SetSecret(&m.AWSAccessKeyID, c, "awsAccessKeyId", h)
	stringattr.SetSecret(&m.AWSSecretAccessKey, c, "awsSecretAccessKey", h)
	stringattr.Set(&m.AWSRoleARN, c, "awsRoleArn")
	stringattr.Set(&m.AWSExternalID, c, "awsExternalId")
	stringattr.Set(&m.AWSRegion, c, "awsRegion")
	stringattr.Set(&m.AWSService, c, "awsService")
	boolattr.Set(&m.UseMTLS, c, "useMTLS")
	stringattr.SetSecret(&m.ClientCertificate, c, "clientCert", h)
	stringattr.SetSecret(&m.ClientKey, c, "clientKey", h)
	stringattr.SetSecret(&m.CACertificate, c, "caCert", h)
	boolattr.Set(&m.RFC9421SigningEnabled, c, "rfc9421SigningEnabled")
	stringattr.SetSecret(&m.RFC9421PrivateKey, c, "rfc9421PrivateKey", h)
	stringattr.Set(&m.RFC9421KeyID, c, "rfc9421KeyId")
	stringattr.Set(&m.RFC9421Components, c, "rfc9421Components")
	floatattr.Set(&m.RFC9421SignatureTTL, c, "rfc9421SignatureTTL")
	boolattr.Set(&m.Insecure, c, "insecure")
	boolattr.Set(&m.IncludeHeadersInContext, c, "includeHeadersInContext")
	boolattr.Set(&m.UseStaticIPs, c, "useStaticIps")
}

func (m *HTTPConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *HTTPConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *HTTPConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
