// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestHTTPConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "http_connector")
	testacc.RunWithDestroyCheck(t, "descope_http_connector",
		// create a new http connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				base_url = "bceszn6"
				authentication = {
    							bearer_token = "xhmqmkcfhe4mk6"
    						}
				headers = { "X-Plain" = "g6htpmp" }
				secret_headers = { "X-Secret" = "j57dfuysuuapr" }
				hmac_secret = "ooxzct5yxz"
				aws_auth_type = "none"
				aws_access_key_id = null
				aws_secret_access_key = null
				aws_role_arn = null
				aws_external_id = null
				aws_region = null
				aws_service = null
				use_mtls = true
				client_certificate = "ag66debo7j"
				client_key = "ade26grht"
				ca_certificate = "7h545x"
				rfc9421_signing_enabled = false
				rfc9421_private_key = null
				rfc9421_key_id = null
				rfc9421_components = null
				rfc9421_signature_ttl = null
				insecure = false
				include_headers_in_context = true
				use_static_ips = false
			`),
			Check: c.Check(map[string]any{
				"id":                          testacc.AttributeIsSet,
				"project_id":                  testacc.AttributeIsSet,
				"name":                        c.Name,
				"description":                 "",
				"disabled":                    false,
				"base_url":                    "bceszn6",
				"authentication.bearer_token": "xhmqmkcfhe4mk6",
				"headers.X-Plain":             "g6htpmp",
				"secret_headers.X-Secret":     "j57dfuysuuapr",
				"hmac_secret":                 "ooxzct5yxz",
				"aws_auth_type":               "none",
				"aws_access_key_id":           testacc.AttributeIsNotSet,
				"aws_secret_access_key":       testacc.AttributeIsNotSet,
				"aws_role_arn":                "",
				"aws_external_id":             "",
				"aws_region":                  "",
				"aws_service":                 "",
				"use_mtls":                    true,
				"client_certificate":          "ag66debo7j",
				"client_key":                  "ade26grht",
				"ca_certificate":              "7h545x",
				"rfc9421_signing_enabled":     false,
				"rfc9421_private_key":         testacc.AttributeIsNotSet,
				"rfc9421_key_id":              "",
				"rfc9421_components":          "",
				"rfc9421_signature_ttl":       "300",
				"insecure":                    false,
				"include_headers_in_context":  true,
				"use_static_ips":              false,
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				base_url = "yruwlv4"
				authentication = {
    							bearer_token = "r6zxhdnnw7dqoq"
    						}
				headers = { "X-Plain" = "7xiojfk" }
				secret_headers = { "X-Secret" = "yh4n7htn6b32r" }
				hmac_secret = "twukowwuij"
				aws_auth_type = "none"
				aws_access_key_id = null
				aws_secret_access_key = null
				aws_role_arn = null
				aws_external_id = null
				aws_region = null
				aws_service = null
				use_mtls = true
				client_certificate = "cwmdh2gtfc"
				client_key = "ez6okur65"
				ca_certificate = "azwal3"
				rfc9421_signing_enabled = false
				rfc9421_private_key = null
				rfc9421_key_id = null
				rfc9421_components = null
				rfc9421_signature_ttl = null
				insecure = true
				include_headers_in_context = false
				use_static_ips = true
			`),
			Check: c.Check(map[string]any{
				"description":                 "updated",
				"disabled":                    true,
				"base_url":                    "yruwlv4",
				"authentication.bearer_token": "r6zxhdnnw7dqoq",
				"headers.X-Plain":             "7xiojfk",
				"secret_headers.X-Secret":     "yh4n7htn6b32r",
				"hmac_secret":                 "twukowwuij",
				"aws_auth_type":               "none",
				"aws_access_key_id":           testacc.AttributeIsNotSet,
				"aws_secret_access_key":       testacc.AttributeIsNotSet,
				"aws_role_arn":                "",
				"aws_external_id":             "",
				"aws_region":                  "",
				"aws_service":                 "",
				"use_mtls":                    true,
				"client_certificate":          "cwmdh2gtfc",
				"client_key":                  "ez6okur65",
				"ca_certificate":              "azwal3",
				"rfc9421_signing_enabled":     false,
				"rfc9421_private_key":         testacc.AttributeIsNotSet,
				"rfc9421_key_id":              "",
				"rfc9421_components":          "",
				"rfc9421_signature_ttl":       "300",
				"insecure":                    true,
				"include_headers_in_context":  false,
				"use_static_ips":              true,
			}),
		},
	)
}
