// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestHubSpotConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "hubspot_connector")
	testacc.RunWithDestroyCheck(t, "descope_hubspot_connector",
		// create a new hubspot connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				access_token = "ssrho3t3233"
				base_url = "bceszn6"
				use_static_ips = false
			`),
			Check: c.Check(map[string]any{
				"id":             testacc.AttributeIsSet,
				"project_id":     testacc.AttributeIsSet,
				"name":           c.Name,
				"description":    "",
				"disabled":       false,
				"access_token":   "ssrho3t3233",
				"base_url":       "bceszn6",
				"use_static_ips": false,
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				access_token = "euailfbwczd"
				base_url = "yruwlv4"
				use_static_ips = true
			`),
			Check: c.Check(map[string]any{
				"description":    "updated",
				"disabled":       true,
				"access_token":   "euailfbwczd",
				"base_url":       "yruwlv4",
				"use_static_ips": true,
			}),
		},
	)
}
