// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_intercom_connector is a standalone Intercom connector with a server-assigned id.

var IntercomConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Intercom connector and its configuration in a Descope project. Orchestrate customer identity information from your Descope user journey with the Intercom connector.",
	Attributes:          IntercomConnectorAttributes,
}

var IntercomConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"token":  stringattr.SecretRequired(),
	"region": stringattr.Default("US"),
}

// Model

type IntercomConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	Token  stringattr.Type `tfsdk:"token"`
	Region stringattr.Type `tfsdk:"region"`
}

func (m *IntercomConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "intercom"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *IntercomConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *IntercomConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.Token, c, "token")
	stringattr.Get(m.Region, c, "region")
	return c
}

func (m *IntercomConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.SetSecret(&m.Token, c, "token", h)
	stringattr.Set(&m.Region, c, "region")
}

func (m *IntercomConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *IntercomConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *IntercomConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
