// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_lokalise_connector is a standalone Lokalise connector with a server-assigned id.

var LokaliseConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Lokalise connector and its configuration in a Descope project. Localize the language of your login and user journey screens with the Lokalise connector. Screen texts are pushed to your Lokalise project as keys, translated inside Lokalise by your team, and pulled back once ready.",
	Attributes:          LokaliseConnectorAttributes,
}

var LokaliseConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"api_token":         stringattr.SecretRequired(),
	"config_project_id": stringattr.Required(),
}

// Model

type LokaliseConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	APIToken        stringattr.Type `tfsdk:"api_token"`
	ConfigProjectID stringattr.Type `tfsdk:"config_project_id"`
}

func (m *LokaliseConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "lokalise"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *LokaliseConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *LokaliseConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.APIToken, c, "apiToken")
	stringattr.Get(m.ConfigProjectID, c, "projectId")
	return c
}

func (m *LokaliseConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.SetSecret(&m.APIToken, c, "apiToken", h)
	stringattr.Set(&m.ConfigProjectID, c, "projectId")
}

func (m *LokaliseConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *LokaliseConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *LokaliseConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
