// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestNewRelicConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "newrelic_connector")
	testacc.RunWithDestroyCheck(t, "descope_newrelic_connector",
		// create a new newrelic connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				api_key = "mhvece"
				data_center = "wjih4vgzrt"
				audit_enabled = true
				audit_filters = [{ key = "actions", operator = "includes", values = ["kekpon4oj34w"] }]
				troubleshoot_log_enabled = false
				override_logs_prefix = true
				logs_prefix = "descope."
			`),
			Check: c.Check(map[string]any{
				"id":                       testacc.AttributeIsSet,
				"project_id":               testacc.AttributeIsSet,
				"name":                     c.Name,
				"description":              "",
				"disabled":                 false,
				"api_key":                  "mhvece",
				"data_center":              "wjih4vgzrt",
				"audit_enabled":            true,
				"audit_filters.0.values":   []string{"kekpon4oj34w"},
				"troubleshoot_log_enabled": false,
				"override_logs_prefix":     true,
				"logs_prefix":              "descope.",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				api_key = "24ynkg"
				data_center = "jr2srlyv3g"
				audit_enabled = true
				audit_filters = [{ key = "actions", operator = "includes", values = ["po4by43vyqpb"] }]
				troubleshoot_log_enabled = true
				override_logs_prefix = true
				logs_prefix = "descope."
			`),
			Check: c.Check(map[string]any{
				"description":              "updated",
				"disabled":                 true,
				"api_key":                  "24ynkg",
				"data_center":              "jr2srlyv3g",
				"audit_enabled":            true,
				"audit_filters.0.values":   []string{"po4by43vyqpb"},
				"troubleshoot_log_enabled": true,
				"override_logs_prefix":     true,
				"logs_prefix":              "descope.",
			}),
		},
	)
}
