// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/listattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/objattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/strmapattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_opentelemetry_connector is a standalone OpenTelemetry connector with a server-assigned id.

var OpenTelemetryConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a OpenTelemetry connector and its configuration in a Descope project. Send audit events and troubleshooting logs to an OpenTelemetry-compatible endpoint using OTLP over HTTP or gRPC.",
	Attributes:          OpenTelemetryConnectorAttributes,
}

var OpenTelemetryConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"endpoint":                 stringattr.Required(),
	"protocol":                 stringattr.Default("http", stringvalidator.OneOf("http", "grpc")),
	"authentication":           objattr.Default(HTTPAuthFieldDefault, HTTPAuthFieldAttributes, HTTPAuthFieldValidator),
	"headers":                  strmapattr.Default(),
	"secret_headers":           strmapattr.Secret(),
	"insecure":                 boolattr.Default(false),
	"audit_enabled":            boolattr.Default(true),
	"audit_filters":            listattr.Default[AuditFilterFieldModel](AuditFilterFieldAttributes),
	"troubleshoot_log_enabled": boolattr.Default(false),
}

// Model

type OpenTelemetryConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	Endpoint               stringattr.Type                      `tfsdk:"endpoint"`
	Protocol               stringattr.Type                      `tfsdk:"protocol"`
	Authentication         objattr.Type[HTTPAuthFieldModel]     `tfsdk:"authentication"`
	Headers                strmapattr.Type                      `tfsdk:"headers"`
	SecretHeaders          strmapattr.Type                      `tfsdk:"secret_headers"`
	Insecure               boolattr.Type                        `tfsdk:"insecure"`
	AuditEnabled           boolattr.Type                        `tfsdk:"audit_enabled"`
	AuditFilters           listattr.Type[AuditFilterFieldModel] `tfsdk:"audit_filters"`
	TroubleshootLogEnabled boolattr.Type                        `tfsdk:"troubleshoot_log_enabled"`
}

func (m *OpenTelemetryConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "opentelemetry"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	m.Validate(h)
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *OpenTelemetryConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

func (m *OpenTelemetryConnectorModel) Validate(h *helpers.Handler) {
	if !m.AuditFilters.IsEmpty() && !m.AuditEnabled.IsUnknown() && !m.AuditEnabled.IsNull() && !m.AuditEnabled.ValueBool() {
		h.Conflict("The audit_filters field cannot be used when audit_enabled isn't set to true")
	}
}

// Configuration

func (m *OpenTelemetryConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.Endpoint, c, "endpoint")
	stringattr.Get(m.Protocol, c, "protocol")
	objattr.Get(m.Authentication, c, "authentication", h)
	getSecretObject(m.Headers, m.SecretHeaders, c, "headers", h)
	boolattr.Get(m.Insecure, c, "insecure")
	boolattr.Get(m.AuditEnabled, c, "auditEnabled")
	listattr.Get(m.AuditFilters, c, "auditFilters", h)
	boolattr.Get(m.TroubleshootLogEnabled, c, "troubleshootLogEnabled")
	return c
}

func (m *OpenTelemetryConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.Endpoint, c, "endpoint")
	stringattr.Set(&m.Protocol, c, "protocol")
	objattr.Set(&m.Authentication, c, "authentication", h)
	setSecretObject(&m.Headers, &m.SecretHeaders, c, "headers", h)
	boolattr.Set(&m.Insecure, c, "insecure")
	boolattr.Set(&m.AuditEnabled, c, "auditEnabled")
	listattr.Set(&m.AuditFilters, c, "auditFilters", h)
	boolattr.Set(&m.TroubleshootLogEnabled, c, "troubleshootLogEnabled")
}

func (m *OpenTelemetryConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *OpenTelemetryConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *OpenTelemetryConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
