// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestPendoConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "pendo_connector")
	testacc.RunWithDestroyCheck(t, "descope_pendo_connector",
		// create a new pendo connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				base_url = "https://data.pendo.io"
				integration_key = "4m6paoe6j55zuq"
				audit_enabled = true
				audit_filters = [{ key = "actions", operator = "includes", values = ["kekpon4oj34w"] }]
				troubleshoot_log_enabled = false
				mask_pii = false
			`),
			Check: c.Check(map[string]any{
				"id":                       testacc.AttributeIsSet,
				"project_id":               testacc.AttributeIsSet,
				"name":                     c.Name,
				"description":              "",
				"disabled":                 false,
				"base_url":                 "https://data.pendo.io",
				"integration_key":          "4m6paoe6j55zuq",
				"audit_enabled":            true,
				"audit_filters.0.values":   []string{"kekpon4oj34w"},
				"troubleshoot_log_enabled": false,
				"mask_pii":                 false,
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				base_url = "https://data.pendo.io"
				integration_key = "nfqem74lptam5m"
				audit_enabled = true
				audit_filters = [{ key = "actions", operator = "includes", values = ["po4by43vyqpb"] }]
				troubleshoot_log_enabled = true
				mask_pii = true
			`),
			Check: c.Check(map[string]any{
				"description":              "updated",
				"disabled":                 true,
				"base_url":                 "https://data.pendo.io",
				"integration_key":          "nfqem74lptam5m",
				"audit_enabled":            true,
				"audit_filters.0.values":   []string{"po4by43vyqpb"},
				"troubleshoot_log_enabled": true,
				"mask_pii":                 true,
			}),
		},
	)
}
