// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/floatattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_radar_connector is a standalone Radar connector with a server-assigned id.

var RadarConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Radar connector and its configuration in a Descope project. Get address autocompletions from Radar Autocomplete API.",
	Attributes:          RadarConnectorAttributes,
}

var RadarConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"public_api_key": stringattr.Required(),
	"address_types":  stringattr.Default(""),
	"language":       stringattr.Default(""),
	"region":         stringattr.Default(""),
	"limit":          floatattr.Default(5),
}

// Model

type RadarConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	PublicAPIKey stringattr.Type `tfsdk:"public_api_key"`
	AddressTypes stringattr.Type `tfsdk:"address_types"`
	Language     stringattr.Type `tfsdk:"language"`
	Region       stringattr.Type `tfsdk:"region"`
	Limit        floatattr.Type  `tfsdk:"limit"`
}

func (m *RadarConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "radar"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *RadarConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *RadarConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.PublicAPIKey, c, "publicApiKey")
	stringattr.Get(m.AddressTypes, c, "addressTypes")
	stringattr.Get(m.Language, c, "language")
	stringattr.Get(m.Region, c, "region")
	floatattr.Get(m.Limit, c, "limit")
	return c
}

func (m *RadarConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.PublicAPIKey, c, "publicApiKey")
	stringattr.Set(&m.AddressTypes, c, "addressTypes")
	stringattr.Set(&m.Language, c, "language")
	stringattr.Set(&m.Region, c, "region")
	floatattr.Set(&m.Limit, c, "limit")
}

func (m *RadarConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *RadarConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *RadarConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
