// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestRecaptchaConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "recaptcha_connector")
	testacc.RunWithDestroyCheck(t, "descope_recaptcha_connector",
		// create a new recaptcha connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				site_key = "ikzbbly"
				secret_key = "wi4bhwt7a"
				override_assessment = true
				assessment_score = 15
			`),
			Check: c.Check(map[string]any{
				"id":                  testacc.AttributeIsSet,
				"project_id":          testacc.AttributeIsSet,
				"name":                c.Name,
				"description":         "",
				"disabled":            false,
				"site_key":            "ikzbbly",
				"secret_key":          "wi4bhwt7a",
				"override_assessment": true,
				"assessment_score":    15,
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				site_key = "u5wekmr"
				secret_key = "ub2ewdlnz"
				override_assessment = true
				assessment_score = 16
			`),
			Check: c.Check(map[string]any{
				"description":         "updated",
				"disabled":            true,
				"site_key":            "u5wekmr",
				"secret_key":          "ub2ewdlnz",
				"override_assessment": true,
				"assessment_score":    16,
			}),
		},
	)
}
