// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/floatattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_recaptcha_connector is a standalone reCAPTCHA v3 connector with a server-assigned id.

var RecaptchaConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a reCAPTCHA v3 connector and its configuration in a Descope project. Prevent bot attacks on your login pages with the reCAPTCHA v3 connector.",
	Attributes:          RecaptchaConnectorAttributes,
}

var RecaptchaConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"site_key":            stringattr.Required(),
	"secret_key":          stringattr.SecretRequired(),
	"override_assessment": boolattr.Default(false),
	"assessment_score":    floatattr.Default(0.5),
}

// Model

type RecaptchaConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	SiteKey            stringattr.Type `tfsdk:"site_key"`
	SecretKey          stringattr.Type `tfsdk:"secret_key"`
	OverrideAssessment boolattr.Type   `tfsdk:"override_assessment"`
	AssessmentScore    floatattr.Type  `tfsdk:"assessment_score"`
}

func (m *RecaptchaConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "recaptcha"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *RecaptchaConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *RecaptchaConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.SiteKey, c, "siteKey")
	stringattr.Get(m.SecretKey, c, "secretKey")
	boolattr.Get(m.OverrideAssessment, c, "overrideAssessment")
	floatattr.Get(m.AssessmentScore, c, "assessmentScore")
	return c
}

func (m *RecaptchaConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.SiteKey, c, "siteKey")
	stringattr.SetSecret(&m.SecretKey, c, "secretKey", h)
	boolattr.Set(&m.OverrideAssessment, c, "overrideAssessment")
	floatattr.Set(&m.AssessmentScore, c, "assessmentScore")
}

func (m *RecaptchaConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *RecaptchaConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *RecaptchaConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
