// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestRecaptchaEnterpriseConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "recaptcha_enterprise_connector")
	testacc.RunWithDestroyCheck(t, "descope_recaptcha_enterprise_connector",
		// create a new recaptcha-enterprise connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				config_project_id = "yhw7b6yel"
				site_key = "ikzbbly"
				api_key = "mhvece"
				base_url = "https://www.google.com"
				action = "xwjyy2"
				override_assessment = true
				bot_threshold = 12
				assessment_score = 15
			`),
			Check: c.Check(map[string]any{
				"id":                  testacc.AttributeIsSet,
				"project_id":          testacc.AttributeIsSet,
				"name":                c.Name,
				"description":         "",
				"disabled":            false,
				"config_project_id":   "yhw7b6yel",
				"site_key":            "ikzbbly",
				"api_key":             "mhvece",
				"base_url":            "https://www.google.com",
				"action":              "xwjyy2",
				"override_assessment": true,
				"bot_threshold":       12,
				"assessment_score":    15,
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				config_project_id = "kyt3656wh"
				site_key = "u5wekmr"
				api_key = "24ynkg"
				base_url = "https://www.google.com"
				action = "xtypph"
				override_assessment = true
				bot_threshold = 13
				assessment_score = 16
			`),
			Check: c.Check(map[string]any{
				"description":         "updated",
				"disabled":            true,
				"config_project_id":   "kyt3656wh",
				"site_key":            "u5wekmr",
				"api_key":             "24ynkg",
				"base_url":            "https://www.google.com",
				"action":              "xtypph",
				"override_assessment": true,
				"bot_threshold":       13,
				"assessment_score":    16,
			}),
		},
	)
}
