// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_rnd_reassigned_connector is a standalone RND Reassigned Numbers connector with a server-assigned id.

var RndReassignedConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a RND Reassigned Numbers connector and its configuration in a Descope project. Query the FCC Reassigned Numbers Database (RND) to validate whether telephone numbers have been permanently disconnected (reassigned) since a specific date. Helps obtain Safe Harbor from TCPA liability by checking the most recent database update.",
	Attributes:          RndReassignedConnectorAttributes,
}

var RndReassignedConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"company_id":    stringattr.Required(),
	"refresh_token": stringattr.SecretRequired(),
}

// Model

type RndReassignedConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	CompanyID    stringattr.Type `tfsdk:"company_id"`
	RefreshToken stringattr.Type `tfsdk:"refresh_token"`
}

func (m *RndReassignedConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "rnd-reassigned"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *RndReassignedConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *RndReassignedConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.CompanyID, c, "companyId")
	stringattr.Get(m.RefreshToken, c, "refreshToken")
	return c
}

func (m *RndReassignedConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.CompanyID, c, "companyId")
	stringattr.SetSecret(&m.RefreshToken, c, "refreshToken", h)
}

func (m *RndReassignedConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *RndReassignedConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *RndReassignedConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
