// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestRndReassignedConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "rnd_reassigned_connector")
	testacc.RunWithDestroyCheck(t, "descope_rnd_reassigned_connector",
		// create a new rnd-reassigned connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				company_id = "yqviirmjb"
				refresh_token = "4hvoty3txjrk"
			`),
			Check: c.Check(map[string]any{
				"id":            testacc.AttributeIsSet,
				"project_id":    testacc.AttributeIsSet,
				"name":          c.Name,
				"description":   "",
				"disabled":      false,
				"company_id":    "yqviirmjb",
				"refresh_token": "4hvoty3txjrk",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				company_id = "hkv6keql4"
				refresh_token = "3ozvy3wt3bhj"
			`),
			Check: c.Check(map[string]any{
				"description":   "updated",
				"disabled":      true,
				"company_id":    "hkv6keql4",
				"refresh_token": "3ozvy3wt3bhj",
			}),
		},
	)
}
