// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_salesforce_connector is a standalone Salesforce connector with a server-assigned id.

var SalesforceConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Salesforce connector and its configuration in a Descope project. Run SQL queries to retrieve user roles, profiles, account status, and more with the Salesforce connector.",
	Attributes:          SalesforceConnectorAttributes,
}

var SalesforceConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"base_url":      stringattr.Required(),
	"client_id":     stringattr.Required(),
	"client_secret": stringattr.SecretRequired(),
	"version":       stringattr.Required(),
}

// Model

type SalesforceConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	BaseURL      stringattr.Type `tfsdk:"base_url"`
	ClientID     stringattr.Type `tfsdk:"client_id"`
	ClientSecret stringattr.Type `tfsdk:"client_secret"`
	Version      stringattr.Type `tfsdk:"version"`
}

func (m *SalesforceConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "salesforce"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *SalesforceConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *SalesforceConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.BaseURL, c, "baseUrl")
	stringattr.Get(m.ClientID, c, "clientId")
	stringattr.Get(m.ClientSecret, c, "clientSecret")
	stringattr.Get(m.Version, c, "version")
	return c
}

func (m *SalesforceConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.BaseURL, c, "baseUrl")
	stringattr.Set(&m.ClientID, c, "clientId")
	stringattr.SetSecret(&m.ClientSecret, c, "clientSecret", h)
	stringattr.Set(&m.Version, c, "version")
}

func (m *SalesforceConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *SalesforceConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *SalesforceConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
