// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_salesforce_marketing_cloud_connector is a standalone Salesforce Marketing Cloud connector with a server-assigned id.

var SalesforceMarketingCloudConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Salesforce Marketing Cloud connector and its configuration in a Descope project. Send transactional messages with the Salesforce Marketing Cloud connector.",
	Attributes:          SalesforceMarketingCloudConnectorAttributes,
}

var SalesforceMarketingCloudConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"subdomain":     stringattr.Required(),
	"client_id":     stringattr.Required(),
	"client_secret": stringattr.SecretRequired(),
	"scope":         stringattr.Default(""),
	"account_id":    stringattr.Default(""),
}

// Model

type SalesforceMarketingCloudConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	Subdomain    stringattr.Type `tfsdk:"subdomain"`
	ClientID     stringattr.Type `tfsdk:"client_id"`
	ClientSecret stringattr.Type `tfsdk:"client_secret"`
	Scope        stringattr.Type `tfsdk:"scope"`
	AccountID    stringattr.Type `tfsdk:"account_id"`
}

func (m *SalesforceMarketingCloudConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "salesforce-marketing-cloud"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *SalesforceMarketingCloudConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *SalesforceMarketingCloudConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.Subdomain, c, "subdomain")
	stringattr.Get(m.ClientID, c, "clientId")
	stringattr.Get(m.ClientSecret, c, "clientSecret")
	stringattr.Get(m.Scope, c, "scope")
	stringattr.Get(m.AccountID, c, "accountId")
	return c
}

func (m *SalesforceMarketingCloudConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.Subdomain, c, "subdomain")
	stringattr.Set(&m.ClientID, c, "clientId")
	stringattr.SetSecret(&m.ClientSecret, c, "clientSecret", h)
	stringattr.Set(&m.Scope, c, "scope")
	stringattr.Set(&m.AccountID, c, "accountId")
}

func (m *SalesforceMarketingCloudConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *SalesforceMarketingCloudConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *SalesforceMarketingCloudConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
