// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_segment_connector is a standalone Segment connector with a server-assigned id.

var SegmentConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Segment connector and its configuration in a Descope project. Orchestrate customer identity traits and signals from your Descope user journey with the Segment connector.",
	Attributes:          SegmentConnectorAttributes,
}

var SegmentConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"write_key":         stringattr.SecretRequired(),
	"host":              stringattr.Default(""),
	"browser_analytics": boolattr.Default(false),
	"public_write_key":  stringattr.Default(""),
}

// Model

type SegmentConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	WriteKey         stringattr.Type `tfsdk:"write_key"`
	Host             stringattr.Type `tfsdk:"host"`
	BrowserAnalytics boolattr.Type   `tfsdk:"browser_analytics"`
	PublicWriteKey   stringattr.Type `tfsdk:"public_write_key"`
}

func (m *SegmentConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "segment"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	m.Validate(h)
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *SegmentConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

func (m *SegmentConnectorModel) Validate(h *helpers.Handler) {
	if m.PublicWriteKey.ValueString() != "" && !m.BrowserAnalytics.IsUnknown() && !m.BrowserAnalytics.ValueBool() {
		h.Conflict("The public_write_key field cannot be used unless browser_analytics is set to true")
	}
	if !m.PublicWriteKey.IsUnknown() && m.PublicWriteKey.ValueString() == "" && m.BrowserAnalytics.ValueBool() {
		h.Conflict("The public_write_key field is required when browser_analytics is set to true")
	}
}

// Configuration

func (m *SegmentConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.WriteKey, c, "writeKey")
	stringattr.Get(m.Host, c, "host")
	boolattr.Get(m.BrowserAnalytics, c, "browserAnalytics")
	stringattr.Get(m.PublicWriteKey, c, "publicWriteKey")
	return c
}

func (m *SegmentConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.SetSecret(&m.WriteKey, c, "writeKey", h)
	stringattr.Set(&m.Host, c, "host")
	boolattr.Set(&m.BrowserAnalytics, c, "browserAnalytics")
	stringattr.Set(&m.PublicWriteKey, c, "publicWriteKey")
}

func (m *SegmentConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *SegmentConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *SegmentConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
