// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestSegmentConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "segment_connector")
	testacc.RunWithDestroyCheck(t, "descope_segment_connector",
		// create a new segment connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				write_key = "vs2jik2d"
				host = "i5ak"
				browser_analytics = true
				public_write_key = "qhzb4w6uivmykj"
			`),
			Check: c.Check(map[string]any{
				"id":                testacc.AttributeIsSet,
				"project_id":        testacc.AttributeIsSet,
				"name":              c.Name,
				"description":       "",
				"disabled":          false,
				"write_key":         "vs2jik2d",
				"host":              "i5ak",
				"browser_analytics": true,
				"public_write_key":  "qhzb4w6uivmykj",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				write_key = "jrrspdel"
				host = "tpqi"
				browser_analytics = true
				public_write_key = "6ebqlfxnkdpl7e"
			`),
			Check: c.Check(map[string]any{
				"description":       "updated",
				"disabled":          true,
				"write_key":         "jrrspdel",
				"host":              "tpqi",
				"browser_analytics": true,
				"public_write_key":  "6ebqlfxnkdpl7e",
			}),
		},
	)
}
