// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_ses_connector is a standalone AWS SES connector with a server-assigned id.

var SESConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a AWS SES connector and its configuration in a Descope project. Send emails through Amazon Simple Email Service (SES).",
	Attributes:          SESConnectorAttributes,
}

var SESConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"auth_type":         stringattr.Default("credentials", stringvalidator.OneOf("", "credentials", "assumeRole")),
	"access_key_id":     stringattr.SecretOptional(),
	"secret_access_key": stringattr.SecretOptional(),
	"role_arn":          stringattr.Default(""),
	"external_id":       stringattr.Default(""),
	"region":            stringattr.Required(),
	"endpoint":          stringattr.Default(""),
	"sender_email":      stringattr.Required(),
	"sender_name":       stringattr.Default(""),
}

// Model

type SESConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	AuthType        stringattr.Type `tfsdk:"auth_type"`
	AccessKeyID     stringattr.Type `tfsdk:"access_key_id"`
	SecretAccessKey stringattr.Type `tfsdk:"secret_access_key"`
	RoleARN         stringattr.Type `tfsdk:"role_arn"`
	ExternalID      stringattr.Type `tfsdk:"external_id"`
	Region          stringattr.Type `tfsdk:"region"`
	Endpoint        stringattr.Type `tfsdk:"endpoint"`
	SenderEmail     stringattr.Type `tfsdk:"sender_email"`
	SenderName      stringattr.Type `tfsdk:"sender_name"`
}

func (m *SESConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "ses"
	m.Validate(h)
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *SESConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

func (m *SESConnectorModel) Validate(h *helpers.Handler) {
	if m.AccessKeyID.ValueString() != "" && m.AuthType.ValueString() != "" && m.AuthType.ValueString() != "credentials" {
		h.Conflict("The access_key_id field can only be used when auth_type is set to 'credentials'")
	}
	if m.AccessKeyID.ValueString() == "" && !m.AccessKeyID.IsUnknown() && m.AuthType.ValueString() == "credentials" {
		h.Conflict("The access_key_id field is required when auth_type is set to 'credentials'")
	}
	if m.SecretAccessKey.ValueString() != "" && m.AuthType.ValueString() != "" && m.AuthType.ValueString() != "credentials" {
		h.Conflict("The secret_access_key field can only be used when auth_type is set to 'credentials'")
	}
	if m.SecretAccessKey.ValueString() == "" && !m.SecretAccessKey.IsUnknown() && m.AuthType.ValueString() == "credentials" {
		h.Conflict("The secret_access_key field is required when auth_type is set to 'credentials'")
	}
	if m.RoleARN.ValueString() != "" && m.AuthType.ValueString() != "" && m.AuthType.ValueString() != "assumeRole" {
		h.Conflict("The role_arn field can only be used when auth_type is set to 'assumeRole'")
	}
	if m.RoleARN.ValueString() == "" && !m.RoleARN.IsUnknown() && m.AuthType.ValueString() == "assumeRole" {
		h.Conflict("The role_arn field is required when auth_type is set to 'assumeRole'")
	}
	if m.ExternalID.ValueString() != "" && m.AuthType.ValueString() != "" && m.AuthType.ValueString() != "assumeRole" {
		h.Conflict("The external_id field can only be used when auth_type is set to 'assumeRole'")
	}
	if m.ExternalID.ValueString() == "" && !m.ExternalID.IsUnknown() && m.AuthType.ValueString() == "assumeRole" {
		h.Conflict("The external_id field is required when auth_type is set to 'assumeRole'")
	}
}

// Configuration

func (m *SESConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.AuthType, c, "authType")
	stringattr.Get(m.AccessKeyID, c, "accessKeyId")
	stringattr.Get(m.SecretAccessKey, c, "secretAccessKey")
	stringattr.Get(m.RoleARN, c, "roleArn")
	stringattr.Get(m.ExternalID, c, "externalId")
	stringattr.Get(m.Region, c, "region")
	stringattr.Get(m.Endpoint, c, "endpoint")
	stringattr.Get(m.SenderEmail, c, "fromEmail")
	stringattr.Get(m.SenderName, c, "fromName")
	return c
}

func (m *SESConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.AuthType, c, "authType")
	stringattr.SetSecret(&m.AccessKeyID, c, "accessKeyId", h)
	stringattr.SetSecret(&m.SecretAccessKey, c, "secretAccessKey", h)
	stringattr.Set(&m.RoleARN, c, "roleArn")
	stringattr.Set(&m.ExternalID, c, "externalId")
	stringattr.Set(&m.Region, c, "region")
	stringattr.Set(&m.Endpoint, c, "endpoint")
	stringattr.Set(&m.SenderEmail, c, "fromEmail")
	stringattr.Set(&m.SenderName, c, "fromName")
}

func (m *SESConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *SESConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *SESConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
