// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestSESConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "ses_connector")
	testacc.RunWithDestroyCheck(t, "descope_ses_connector",
		// create a new ses connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				auth_type = "credentials"
				access_key_id = "ezzrllbqu22"
				secret_access_key = "xiyuadzk4w64hog"
				role_arn = null
				external_id = null
				region = "y2l5fg"
				endpoint = "w27xxsgz"
				sender_email = "pkik6p7rr"
				sender_name = "qquro4c7"
			`),
			Check: c.Check(map[string]any{
				"id":                testacc.AttributeIsSet,
				"project_id":        testacc.AttributeIsSet,
				"name":              c.Name,
				"description":       "",
				"auth_type":         "credentials",
				"access_key_id":     "ezzrllbqu22",
				"secret_access_key": "xiyuadzk4w64hog",
				"role_arn":          "",
				"external_id":       "",
				"region":            "y2l5fg",
				"endpoint":          "w27xxsgz",
				"sender_email":      "pkik6p7rr",
				"sender_name":       "qquro4c7",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				auth_type = "credentials"
				access_key_id = "an2mu73kjot"
				secret_access_key = "vzjnvlzyyvbdwad"
				role_arn = null
				external_id = null
				region = "versrj"
				endpoint = "ef4vxrwc"
				sender_email = "macajtsxd"
				sender_name = "amlgf3lm"
			`),
			Check: c.Check(map[string]any{
				"description":       "updated",
				"auth_type":         "credentials",
				"access_key_id":     "an2mu73kjot",
				"secret_access_key": "vzjnvlzyyvbdwad",
				"role_arn":          "",
				"external_id":       "",
				"region":            "versrj",
				"endpoint":          "ef4vxrwc",
				"sender_email":      "macajtsxd",
				"sender_name":       "amlgf3lm",
			}),
		},
	)
}
