// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestSlackConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "slack_connector")
	testacc.RunWithDestroyCheck(t, "descope_slack_connector",
		// create a new slack connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				token = "hrdj5"
			`),
			Check: c.Check(map[string]any{
				"id":          testacc.AttributeIsSet,
				"project_id":  testacc.AttributeIsSet,
				"name":        c.Name,
				"description": "",
				"disabled":    false,
				"token":       "hrdj5",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				token = "fwq3n"
			`),
			Check: c.Check(map[string]any{
				"description": "updated",
				"disabled":    true,
				"token":       "fwq3n",
			}),
		},
	)
}
