// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestSmartlingConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "smartling_connector")
	testacc.RunWithDestroyCheck(t, "descope_smartling_connector",
		// create a new smartling connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				user_identifier = "h2sy3jtqq4rxwi"
				user_secret = "gchtcl2tno"
				account_uid = "7qxonan5tu"
			`),
			Check: c.Check(map[string]any{
				"id":              testacc.AttributeIsSet,
				"project_id":      testacc.AttributeIsSet,
				"name":            c.Name,
				"description":     "",
				"disabled":        false,
				"user_identifier": "h2sy3jtqq4rxwi",
				"user_secret":     "gchtcl2tno",
				"account_uid":     "7qxonan5tu",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				user_identifier = "ucn5dg3jdkmtr6"
				user_secret = "gyufckzfz4"
				account_uid = "b2qanorhpa"
			`),
			Check: c.Check(map[string]any{
				"description":     "updated",
				"disabled":        true,
				"user_identifier": "ucn5dg3jdkmtr6",
				"user_secret":     "gyufckzfz4",
				"account_uid":     "b2qanorhpa",
			}),
		},
	)
}
