// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_smartling_connector is a standalone Smartling connector with a server-assigned id.

var SmartlingConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Smartling connector and its configuration in a Descope project. Localize the language of your login and user journey screens with the Smartling connector.",
	Attributes:          SmartlingConnectorAttributes,
}

var SmartlingConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"user_identifier": stringattr.Required(),
	"user_secret":     stringattr.SecretRequired(),
	"account_uid":     stringattr.Required(),
}

// Model

type SmartlingConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	UserIdentifier stringattr.Type `tfsdk:"user_identifier"`
	UserSecret     stringattr.Type `tfsdk:"user_secret"`
	AccountUID     stringattr.Type `tfsdk:"account_uid"`
}

func (m *SmartlingConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "smartling"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *SmartlingConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *SmartlingConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.UserIdentifier, c, "userIdentifier")
	stringattr.Get(m.UserSecret, c, "userSecret")
	stringattr.Get(m.AccountUID, c, "accountUid")
	return c
}

func (m *SmartlingConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.UserIdentifier, c, "userIdentifier")
	stringattr.SetSecret(&m.UserSecret, c, "userSecret", h)
	stringattr.Set(&m.AccountUID, c, "accountUid")
}

func (m *SmartlingConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *SmartlingConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *SmartlingConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
