// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/floatattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_smtp_connector is a standalone SMTP connector with a server-assigned id.

var SMTPConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a SMTP connector and its configuration in a Descope project. A general purpose SMTP connector for sending emails through your own mail server.",
	Attributes:          SMTPConnectorAttributes,
}

var SMTPConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"host":           stringattr.Required(),
	"port":           floatattr.Default(25),
	"username":       stringattr.Required(),
	"password":       stringattr.SecretRequired(),
	"auth_method":    stringattr.Default("plain", stringvalidator.OneOf("", "plain", "login")),
	"sender_email":   stringattr.Required(),
	"sender_name":    stringattr.Default(""),
	"use_static_ips": boolattr.Default(false),
}

// Model

type SMTPConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	Host         stringattr.Type `tfsdk:"host"`
	Port         floatattr.Type  `tfsdk:"port"`
	Username     stringattr.Type `tfsdk:"username"`
	Password     stringattr.Type `tfsdk:"password"`
	AuthMethod   stringattr.Type `tfsdk:"auth_method"`
	SenderEmail  stringattr.Type `tfsdk:"sender_email"`
	SenderName   stringattr.Type `tfsdk:"sender_name"`
	UseStaticIPs boolattr.Type   `tfsdk:"use_static_ips"`
}

func (m *SMTPConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "smtp"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *SMTPConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *SMTPConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.Host, c, "host")
	floatattr.Get(m.Port, c, "port")
	stringattr.Get(m.Username, c, "username")
	stringattr.Get(m.Password, c, "password")
	stringattr.Get(m.AuthMethod, c, "authMethod")
	stringattr.Get(m.SenderEmail, c, "fromEmail")
	stringattr.Get(m.SenderName, c, "fromName")
	boolattr.Get(m.UseStaticIPs, c, "useStaticIps")
	return c
}

func (m *SMTPConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.Host, c, "host")
	floatattr.Set(&m.Port, c, "port")
	stringattr.Set(&m.Username, c, "username")
	stringattr.SetSecret(&m.Password, c, "password", h)
	stringattr.Set(&m.AuthMethod, c, "authMethod")
	stringattr.Set(&m.SenderEmail, c, "fromEmail")
	stringattr.Set(&m.SenderName, c, "fromName")
	boolattr.Set(&m.UseStaticIPs, c, "useStaticIps")
}

func (m *SMTPConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *SMTPConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *SMTPConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
