// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestSnowflakeConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "snowflake_connector")
	testacc.RunWithDestroyCheck(t, "descope_snowflake_connector",
		// create a new snowflake connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				auth_type = "pat"
				api_key = "mhvece"
				snowflake_user = null
				private_key = null
				private_key_passphrase = null
				account_identifier = null
				site = "7oxa"
				warehouse = "COMPUTE_WH"
				database = "DESCOPE_EXPORT_DB"
				schema = "PUBLIC"
				audit_table = "DESCOPE_AUDIT_LOGS"
				self_provision = true
				audit_enabled = true
				audit_filters = [{ key = "actions", operator = "includes", values = ["kekpon4oj34w"] }]
				min_flush_interval_minutes = 23
				troubleshoot_log_enabled = false
				mask_pii = false
			`),
			Check: c.Check(map[string]any{
				"id":                         testacc.AttributeIsSet,
				"project_id":                 testacc.AttributeIsSet,
				"name":                       c.Name,
				"description":                "",
				"disabled":                   false,
				"auth_type":                  "pat",
				"api_key":                    "mhvece",
				"snowflake_user":             "",
				"private_key":                testacc.AttributeIsNotSet,
				"private_key_passphrase":     testacc.AttributeIsNotSet,
				"account_identifier":         "",
				"site":                       "7oxa",
				"warehouse":                  "COMPUTE_WH",
				"database":                   "DESCOPE_EXPORT_DB",
				"schema":                     "PUBLIC",
				"audit_table":                "DESCOPE_AUDIT_LOGS",
				"self_provision":             true,
				"audit_enabled":              true,
				"audit_filters.0.values":     []string{"kekpon4oj34w"},
				"min_flush_interval_minutes": 23,
				"troubleshoot_log_enabled":   false,
				"mask_pii":                   false,
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				auth_type = "pat"
				api_key = "24ynkg"
				snowflake_user = null
				private_key = null
				private_key_passphrase = null
				account_identifier = null
				site = "gbul"
				warehouse = "COMPUTE_WH"
				database = "DESCOPE_EXPORT_DB"
				schema = "PUBLIC"
				audit_table = "DESCOPE_AUDIT_LOGS"
				self_provision = false
				audit_enabled = true
				audit_filters = [{ key = "actions", operator = "includes", values = ["po4by43vyqpb"] }]
				min_flush_interval_minutes = 24
				troubleshoot_log_enabled = true
				mask_pii = true
			`),
			Check: c.Check(map[string]any{
				"description":                "updated",
				"disabled":                   true,
				"auth_type":                  "pat",
				"api_key":                    "24ynkg",
				"snowflake_user":             "",
				"private_key":                testacc.AttributeIsNotSet,
				"private_key_passphrase":     testacc.AttributeIsNotSet,
				"account_identifier":         "",
				"site":                       "gbul",
				"warehouse":                  "COMPUTE_WH",
				"database":                   "DESCOPE_EXPORT_DB",
				"schema":                     "PUBLIC",
				"audit_table":                "DESCOPE_AUDIT_LOGS",
				"self_provision":             false,
				"audit_enabled":              true,
				"audit_filters.0.values":     []string{"po4by43vyqpb"},
				"min_flush_interval_minutes": 24,
				"troubleshoot_log_enabled":   true,
				"mask_pii":                   true,
			}),
		},
	)
}
