// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestSNSConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "sns_connector")
	testacc.RunWithDestroyCheck(t, "descope_sns_connector",
		// create a new sns connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				auth_type = "credentials"
				access_key_id = "ezzrllbqu22"
				secret_access_key = "xiyuadzk4w64hog"
				role_arn = null
				external_id = null
				region = "lerkfzhwgyfw"
				endpoint = "3afezsw4n4u"
				origination_number = "jc35ogtakdidsqlce"
				sender_id = "2hoqpmrk"
				entity_id = "kvxlj7sm"
				template_id = "si4ja3s6et"
			`),
			Check: c.Check(map[string]any{
				"id":                 testacc.AttributeIsSet,
				"project_id":         testacc.AttributeIsSet,
				"name":               c.Name,
				"description":        "",
				"auth_type":          "credentials",
				"access_key_id":      "ezzrllbqu22",
				"secret_access_key":  "xiyuadzk4w64hog",
				"role_arn":           "",
				"external_id":        "",
				"region":             "lerkfzhwgyfw",
				"endpoint":           "3afezsw4n4u",
				"origination_number": "jc35ogtakdidsqlce",
				"sender_id":          "2hoqpmrk",
				"entity_id":          "kvxlj7sm",
				"template_id":        "si4ja3s6et",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				auth_type = "credentials"
				access_key_id = "an2mu73kjot"
				secret_access_key = "vzjnvlzyyvbdwad"
				role_arn = null
				external_id = null
				region = "n5mx4qhqnlgf"
				endpoint = "jzwwurc6b3p"
				origination_number = "yf5we54rslotj4kho"
				sender_id = "u2rtyrj5"
				entity_id = "fhzrq5ny"
				template_id = "ydr5b2bg5w"
			`),
			Check: c.Check(map[string]any{
				"description":        "updated",
				"auth_type":          "credentials",
				"access_key_id":      "an2mu73kjot",
				"secret_access_key":  "vzjnvlzyyvbdwad",
				"role_arn":           "",
				"external_id":        "",
				"region":             "n5mx4qhqnlgf",
				"endpoint":           "jzwwurc6b3p",
				"origination_number": "yf5we54rslotj4kho",
				"sender_id":          "u2rtyrj5",
				"entity_id":          "fhzrq5ny",
				"template_id":        "ydr5b2bg5w",
			}),
		},
	)
}
