// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestSplunkConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "splunk_connector")
	testacc.RunWithDestroyCheck(t, "descope_splunk_connector",
		// create a new splunk connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				hec_token = "djxzrnkm"
				hec_url = "o3lhr4"
				index = "dpaew"
				audit_enabled = true
				audit_filters = [{ key = "actions", operator = "includes", values = ["kekpon4oj34w"] }]
				troubleshoot_log_enabled = false
			`),
			Check: c.Check(map[string]any{
				"id":                       testacc.AttributeIsSet,
				"project_id":               testacc.AttributeIsSet,
				"name":                     c.Name,
				"description":              "",
				"disabled":                 false,
				"hec_token":                "djxzrnkm",
				"hec_url":                  "o3lhr4",
				"index":                    "dpaew",
				"audit_enabled":            true,
				"audit_filters.0.values":   []string{"kekpon4oj34w"},
				"troubleshoot_log_enabled": false,
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				hec_token = "2w4gmsjz"
				hec_url = "wf7yf6"
				index = "lavv2"
				audit_enabled = true
				audit_filters = [{ key = "actions", operator = "includes", values = ["po4by43vyqpb"] }]
				troubleshoot_log_enabled = true
			`),
			Check: c.Check(map[string]any{
				"description":              "updated",
				"disabled":                 true,
				"hec_token":                "2w4gmsjz",
				"hec_url":                  "wf7yf6",
				"index":                    "lavv2",
				"audit_enabled":            true,
				"audit_filters.0.values":   []string{"po4by43vyqpb"},
				"troubleshoot_log_enabled": true,
			}),
		},
	)
}
