// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"slices"

	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/floatattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_sql_connector is a standalone SQL connector with a server-assigned id.

var SQLConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a SQL connector and its configuration in a Descope project. SQL connector for relational databases including PostgreSQL, MySQL, MariaDB, Microsoft SQL Server (MSSQL), Oracle, CockroachDB, and Amazon Redshift.",
	Attributes:          SQLConnectorAttributes,
}

var SQLConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"engine_name":   stringattr.Required(stringvalidator.OneOf("cockroach", "mariadb", "mysql", "oracle", "postgres", "redshift", "mssql")),
	"database_name": stringattr.Default(""),
	"service_name":  stringattr.Default(""),
	"host":          stringattr.Required(),
	"port":          floatattr.Default(0),
	"username":      stringattr.Required(),
	"password":      stringattr.SecretRequired(),
	"engine_id":     stringattr.Default(""),
}

// Model

type SQLConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	EngineName   stringattr.Type `tfsdk:"engine_name"`
	DatabaseName stringattr.Type `tfsdk:"database_name"`
	ServiceName  stringattr.Type `tfsdk:"service_name"`
	Host         stringattr.Type `tfsdk:"host"`
	Port         floatattr.Type  `tfsdk:"port"`
	Username     stringattr.Type `tfsdk:"username"`
	Password     stringattr.Type `tfsdk:"password"`
	EngineID     stringattr.Type `tfsdk:"engine_id"`
}

func (m *SQLConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "sql"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	m.Validate(h)
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *SQLConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

func (m *SQLConnectorModel) Validate(h *helpers.Handler) {
	if m.DatabaseName.ValueString() != "" && m.EngineName.ValueString() != "" && !slices.Contains([]string{"cockroach", "mariadb", "mysql", "postgres", "redshift", "mssql"}, m.EngineName.ValueString()) {
		h.Conflict("The database_name field can only be used when engine_name is one of [cockroach mariadb mysql postgres redshift mssql]")
	}
	if m.ServiceName.ValueString() != "" && m.EngineName.ValueString() != "" && m.EngineName.ValueString() != "oracle" {
		h.Conflict("The service_name field can only be used when engine_name is set to 'oracle'")
	}
}

// Configuration

func (m *SQLConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.EngineName, c, "engineName")
	stringattr.Get(m.DatabaseName, c, "databaseName")
	stringattr.Get(m.ServiceName, c, "serviceName")
	stringattr.Get(m.Host, c, "host")
	floatattr.Get(m.Port, c, "port")
	stringattr.Get(m.Username, c, "username")
	stringattr.Get(m.Password, c, "password")
	stringattr.Get(m.EngineID, c, "engineId")
	return c
}

func (m *SQLConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.EngineName, c, "engineName")
	stringattr.Set(&m.DatabaseName, c, "databaseName")
	stringattr.Set(&m.ServiceName, c, "serviceName")
	stringattr.Set(&m.Host, c, "host")
	floatattr.Set(&m.Port, c, "port")
	stringattr.Set(&m.Username, c, "username")
	stringattr.SetSecret(&m.Password, c, "password", h)
	stringattr.Set(&m.EngineID, c, "engineId")
}

func (m *SQLConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *SQLConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *SQLConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
