// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestSupabaseConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "supabase_connector")
	testacc.RunWithDestroyCheck(t, "descope_supabase_connector",
		// create a new supabase connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				auth_type = "legacyJWTSecret"
				signing_secret = "7z47p3qqxkpcc"
				private_key = null
				create_users = true
				project_base_url = "bq7uctq453b"
				service_role_api_key = "5wfi6yzcy6ipcznpdr5ddi"
				custom_claims_mapping = {
    							"key" = "qy7xiug7baj44hxxfyu"
    						}
				expiration_time = 21
			`),
			Check: c.Check(map[string]any{
				"id":                        testacc.AttributeIsSet,
				"project_id":                testacc.AttributeIsSet,
				"name":                      c.Name,
				"description":               "",
				"disabled":                  false,
				"auth_type":                 "legacyJWTSecret",
				"signing_secret":            "7z47p3qqxkpcc",
				"private_key":               testacc.AttributeIsNotSet,
				"create_users":              true,
				"project_base_url":          "bq7uctq453b",
				"service_role_api_key":      "5wfi6yzcy6ipcznpdr5ddi",
				"custom_claims_mapping.key": "qy7xiug7baj44hxxfyu",
				"expiration_time":           21,
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				auth_type = "legacyJWTSecret"
				signing_secret = "py55iqnwryyx6"
				private_key = null
				create_users = true
				project_base_url = "ydl2jt3dq3d"
				service_role_api_key = "x5phukknfuo3oxjganhodd"
				custom_claims_mapping = {
    							"key" = "mvxeypsk6hvcctsxkpk"
    						}
				expiration_time = 22
			`),
			Check: c.Check(map[string]any{
				"description":               "updated",
				"disabled":                  true,
				"auth_type":                 "legacyJWTSecret",
				"signing_secret":            "py55iqnwryyx6",
				"private_key":               testacc.AttributeIsNotSet,
				"create_users":              true,
				"project_base_url":          "ydl2jt3dq3d",
				"service_role_api_key":      "x5phukknfuo3oxjganhodd",
				"custom_claims_mapping.key": "mvxeypsk6hvcctsxkpk",
				"expiration_time":           22,
			}),
		},
	)
}
