// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/floatattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/strmapattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_supabase_connector is a standalone Supabase connector with a server-assigned id.

var SupabaseConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Supabase connector and its configuration in a Descope project. Generate external tokens for user authentication in Supabase projects.",
	Attributes:          SupabaseConnectorAttributes,
}

var SupabaseConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"auth_type":             stringattr.Default("legacyJWTSecret", stringvalidator.OneOf("legacyJWTSecret", "jwtSigningKey")),
	"signing_secret":        stringattr.SecretOptional(),
	"private_key":           stringattr.SecretOptional(),
	"create_users":          boolattr.Default(false),
	"project_base_url":      stringattr.Default(""),
	"service_role_api_key":  stringattr.SecretOptional(),
	"custom_claims_mapping": strmapattr.Default(),
	"expiration_time":       floatattr.Default(60),
}

// Model

type SupabaseConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	AuthType            stringattr.Type `tfsdk:"auth_type"`
	SigningSecret       stringattr.Type `tfsdk:"signing_secret"`
	PrivateKey          stringattr.Type `tfsdk:"private_key"`
	CreateUsers         boolattr.Type   `tfsdk:"create_users"`
	ProjectBaseURL      stringattr.Type `tfsdk:"project_base_url"`
	ServiceRoleAPIKey   stringattr.Type `tfsdk:"service_role_api_key"`
	CustomClaimsMapping strmapattr.Type `tfsdk:"custom_claims_mapping"`
	ExpirationTime      floatattr.Type  `tfsdk:"expiration_time"`
}

func (m *SupabaseConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "supabase"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	m.Validate(h)
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *SupabaseConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

func (m *SupabaseConnectorModel) Validate(h *helpers.Handler) {
	if m.SigningSecret.ValueString() != "" && m.AuthType.ValueString() != "" && m.AuthType.ValueString() != "legacyJWTSecret" {
		h.Conflict("The signing_secret field can only be used when auth_type is set to 'legacyJWTSecret'")
	}
	if m.SigningSecret.ValueString() == "" && !m.SigningSecret.IsUnknown() && m.AuthType.ValueString() == "legacyJWTSecret" {
		h.Conflict("The signing_secret field is required when auth_type is set to 'legacyJWTSecret'")
	}
	if m.PrivateKey.ValueString() != "" && m.AuthType.ValueString() != "" && m.AuthType.ValueString() != "jwtSigningKey" {
		h.Conflict("The private_key field can only be used when auth_type is set to 'jwtSigningKey'")
	}
	if m.PrivateKey.ValueString() == "" && !m.PrivateKey.IsUnknown() && m.AuthType.ValueString() == "jwtSigningKey" {
		h.Conflict("The private_key field is required when auth_type is set to 'jwtSigningKey'")
	}
	if m.ProjectBaseURL.ValueString() != "" && !m.CreateUsers.IsUnknown() && !m.CreateUsers.ValueBool() {
		h.Conflict("The project_base_url field cannot be used unless create_users is set to true")
	}
	if !m.ProjectBaseURL.IsUnknown() && m.ProjectBaseURL.ValueString() == "" && m.CreateUsers.ValueBool() {
		h.Conflict("The project_base_url field is required when create_users is set to true")
	}
	if m.ServiceRoleAPIKey.ValueString() != "" && !m.CreateUsers.IsUnknown() && !m.CreateUsers.ValueBool() {
		h.Conflict("The service_role_api_key field cannot be used unless create_users is set to true")
	}
	if !m.ServiceRoleAPIKey.IsUnknown() && m.ServiceRoleAPIKey.ValueString() == "" && m.CreateUsers.ValueBool() {
		h.Conflict("The service_role_api_key field is required when create_users is set to true")
	}
}

// Configuration

func (m *SupabaseConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.AuthType, c, "authType")
	stringattr.Get(m.SigningSecret, c, "signingSecret")
	stringattr.Get(m.PrivateKey, c, "privateKey")
	boolattr.Get(m.CreateUsers, c, "createSupabaseUser")
	stringattr.Get(m.ProjectBaseURL, c, "supabaseUrl")
	stringattr.Get(m.ServiceRoleAPIKey, c, "supabaseServiceRoleKey")
	getObjectField(m.CustomClaimsMapping, c, "customClaimsMapping", h)
	floatattr.Get(m.ExpirationTime, c, "expirationTimeMinutes")
	return c
}

func (m *SupabaseConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.AuthType, c, "authType")
	stringattr.SetSecret(&m.SigningSecret, c, "signingSecret", h)
	stringattr.SetSecret(&m.PrivateKey, c, "privateKey", h)
	boolattr.Set(&m.CreateUsers, c, "createSupabaseUser")
	stringattr.Set(&m.ProjectBaseURL, c, "supabaseUrl")
	stringattr.SetSecret(&m.ServiceRoleAPIKey, c, "supabaseServiceRoleKey", h)
	setObjectField(&m.CustomClaimsMapping, c, "customClaimsMapping", h)
	floatattr.Set(&m.ExpirationTime, c, "expirationTimeMinutes")
}

func (m *SupabaseConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *SupabaseConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *SupabaseConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
