// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestTelesignConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "telesign_connector")
	testacc.RunWithDestroyCheck(t, "descope_telesign_connector",
		// create a new telesign connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				customer_id = "yn5scsxze2"
				api_key = "mhvece"
			`),
			Check: c.Check(map[string]any{
				"id":          testacc.AttributeIsSet,
				"project_id":  testacc.AttributeIsSet,
				"name":        c.Name,
				"description": "",
				"disabled":    false,
				"customer_id": "yn5scsxze2",
				"api_key":     "mhvece",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				customer_id = "2ex5wtgnoc"
				api_key = "24ynkg"
			`),
			Check: c.Check(map[string]any{
				"description": "updated",
				"disabled":    true,
				"customer_id": "2ex5wtgnoc",
				"api_key":     "24ynkg",
			}),
		},
	)
}
