// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_traceable_connector is a standalone Traceable connector with a server-assigned id.

var TraceableConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Traceable connector and its configuration in a Descope project. Identify and respond to fraudulent login activity with the Traceable Digital Fraud Prevention connector.",
	Attributes:          TraceableConnectorAttributes,
}

var TraceableConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"secret_key": stringattr.SecretRequired(),
	"eu_region":  boolattr.Default(false),
}

// Model

type TraceableConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	SecretKey stringattr.Type `tfsdk:"secret_key"`
	EURegion  boolattr.Type   `tfsdk:"eu_region"`
}

func (m *TraceableConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "traceable"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *TraceableConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *TraceableConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.SecretKey, c, "secretKey")
	boolattr.Get(m.EURegion, c, "euRegion")
	return c
}

func (m *TraceableConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.SetSecret(&m.SecretKey, c, "secretKey", h)
	boolattr.Set(&m.EURegion, c, "euRegion")
}

func (m *TraceableConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *TraceableConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *TraceableConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
