// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_twilio_verify_connector is a standalone Twilio Verify connector with a server-assigned id.

var TwilioVerifyConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Twilio Verify connector and its configuration in a Descope project. Send verification codes through the Twilio Verify service.",
	Attributes:          TwilioVerifyConnectorAttributes,
}

var TwilioVerifyConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"account_sid": stringattr.Required(),
	"service_sid": stringattr.Required(),
	"sender":      stringattr.Default(""),
	"auth_token":  stringattr.SecretOptional(),
	"api_key":     stringattr.SecretOptional(),
	"api_secret":  stringattr.SecretOptional(),
}

// Model

type TwilioVerifyConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	AccountSID stringattr.Type `tfsdk:"account_sid"`
	ServiceSID stringattr.Type `tfsdk:"service_sid"`
	Sender     stringattr.Type `tfsdk:"sender"`
	AuthToken  stringattr.Type `tfsdk:"auth_token"`
	APIKey     stringattr.Type `tfsdk:"api_key"`
	APISecret  stringattr.Type `tfsdk:"api_secret"`
}

func (m *TwilioVerifyConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "twilio-verify"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *TwilioVerifyConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *TwilioVerifyConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.AccountSID, c, "accountSid")
	stringattr.Get(m.ServiceSID, c, "verifyServiceSid")
	stringattr.Get(m.Sender, c, "from")
	stringattr.Get(m.AuthToken, c, "authToken")
	stringattr.Get(m.APIKey, c, "apiKey")
	stringattr.Get(m.APISecret, c, "apiSecret")
	switch {
	case m.AuthToken.ValueString() != "":
		c["selectedAuthProp"] = "methodAuthToken"
	default:
		c["selectedAuthProp"] = "methodApiSecret"
	}
	return c
}

func (m *TwilioVerifyConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.AccountSID, c, "accountSid")
	stringattr.Set(&m.ServiceSID, c, "verifyServiceSid")
	stringattr.Set(&m.Sender, c, "from")
	stringattr.SetSecret(&m.AuthToken, c, "authToken", h)
	stringattr.SetSecret(&m.APIKey, c, "apiKey", h)
	stringattr.SetSecret(&m.APISecret, c, "apiSecret", h)
}

func (m *TwilioVerifyConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *TwilioVerifyConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *TwilioVerifyConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
