// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_unibeam_connector is a standalone Unibeam connector with a server-assigned id.

var UnibeamConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Unibeam connector and its configuration in a Descope project. SIM-based authentication and approval using Unibeam's OnSim technology for passwordless authentication and transaction approval.",
	Attributes:          UnibeamConnectorAttributes,
}

var UnibeamConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"base_url":        stringattr.Required(),
	"customer_id":     stringattr.Required(),
	"client_id":       stringattr.Required(),
	"client_secret":   stringattr.SecretRequired(),
	"hmac_secret":     stringattr.SecretRequired(),
	"default_message": stringattr.Default(""),
}

// Model

type UnibeamConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	BaseURL        stringattr.Type `tfsdk:"base_url"`
	CustomerID     stringattr.Type `tfsdk:"customer_id"`
	ClientID       stringattr.Type `tfsdk:"client_id"`
	ClientSecret   stringattr.Type `tfsdk:"client_secret"`
	HMACSecret     stringattr.Type `tfsdk:"hmac_secret"`
	DefaultMessage stringattr.Type `tfsdk:"default_message"`
}

func (m *UnibeamConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "unibeam"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *UnibeamConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *UnibeamConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.BaseURL, c, "baseUrl")
	stringattr.Get(m.CustomerID, c, "customerId")
	stringattr.Get(m.ClientID, c, "clientId")
	stringattr.Get(m.ClientSecret, c, "clientSecret")
	stringattr.Get(m.HMACSecret, c, "hmacSecret")
	stringattr.Get(m.DefaultMessage, c, "defaultMessage")
	return c
}

func (m *UnibeamConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.BaseURL, c, "baseUrl")
	stringattr.Set(&m.CustomerID, c, "customerId")
	stringattr.Set(&m.ClientID, c, "clientId")
	stringattr.SetSecret(&m.ClientSecret, c, "clientSecret", h)
	stringattr.SetSecret(&m.HMACSecret, c, "hmacSecret", h)
	stringattr.Set(&m.DefaultMessage, c, "defaultMessage")
}

func (m *UnibeamConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *UnibeamConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *UnibeamConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
