// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestZeroBounceConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "zerobounce_connector")
	testacc.RunWithDestroyCheck(t, "descope_zerobounce_connector",
		// create a new zerobounce connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				api_key = "mhvece"
				region = "default"
			`),
			Check: c.Check(map[string]any{
				"id":          testacc.AttributeIsSet,
				"project_id":  testacc.AttributeIsSet,
				"name":        c.Name,
				"description": "",
				"disabled":    false,
				"api_key":     "mhvece",
				"region":      "default",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				api_key = "24ynkg"
				region = "default"
			`),
			Check: c.Check(map[string]any{
				"description": "updated",
				"disabled":    true,
				"api_key":     "24ynkg",
				"region":      "default",
			}),
		},
	)
}
