// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_zerobounce_connector is a standalone ZeroBounce connector with a server-assigned id.

var ZeroBounceConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a ZeroBounce connector and its configuration in a Descope project. Email validation with ZeroBounce.",
	Attributes:          ZeroBounceConnectorAttributes,
}

var ZeroBounceConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"api_key": stringattr.SecretRequired(),
	"region":  stringattr.Default("default", stringvalidator.OneOf("default", "us")),
}

// Model

type ZeroBounceConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	APIKey stringattr.Type `tfsdk:"api_key"`
	Region stringattr.Type `tfsdk:"region"`
}

func (m *ZeroBounceConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "zerobounce"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *ZeroBounceConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *ZeroBounceConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.APIKey, c, "apiKey")
	stringattr.Get(m.Region, c, "region")
	return c
}

func (m *ZeroBounceConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.SetSecret(&m.APIKey, c, "apiKey", h)
	stringattr.Set(&m.Region, c, "region")
}

func (m *ZeroBounceConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *ZeroBounceConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *ZeroBounceConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
