name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release
        with:
          release-type: simple
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Trigger Release Workflow
        if: ${{ steps.release.outputs.release_created }}
        run: gh workflow run release.yml -f tag=${{ steps.release.outputs.tag_name }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
