name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  goreleaser:
    name: Run GoReleaser
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Allow goreleaser to access older tag information for changelog
      - name: Setup Repo
        uses: ./.github/actions/ci/setup

      - name: Install Syft
        shell: bash
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/75455f050ab028977a6b625165e2ad3644fcc845/install.sh | sh -s -- -b /usr/local/bin # v1.42.2

      - name: Install Cosign
        uses: sigstore/cosign-installer@ba7bc0a3fef59531c69a25acd34668d6d3fe6f22 # v4.1.0

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}

      - name: Sign Checksums with Cosign
        run: cosign sign-blob --yes dist/*_SHA256SUMS --output-signature dist/*_SHA256SUMS.sig --output-certificate dist/*_SHA256SUMS.pem
        env:
          COSIGN_EXPERIMENTAL: "true"

      - name: Upload Cosign Artifacts
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release upload "$tag" dist/*_SHA256SUMS.sig dist/*_SHA256SUMS.pem --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate SLSA Subject Hashes
        id: hash
        run: |
          cd dist
          sha256sum *.zip *.json > checksums.txt
          echo "hashes=$(base64 -w0 checksums.txt)" >> "$GITHUB_OUTPUT"

  provenance:
    name: Generate SLSA Provenance
    needs: goreleaser
    permissions:
      actions: read
      contents: write
      id-token: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@f7dd8c54c2067bafc12ca7a55595d5ee9b75204a # v2.1.0
    with:
      base64-subjects: "${{ needs.goreleaser.outputs.hashes }}"
      upload-assets: true
