name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        id: release
        with:
          release-type: simple
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Trigger Release Workflow
        if: ${{ steps.release.outputs.release_created }}
        run: gh workflow run release.yml -f tag=${{ steps.release.outputs.tag_name }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
